### ISSUE TITLE
Cannot run logcat

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#1]
adbd is running so I can use adb shell to get into the phone, but neither adb logcat nor logcat in adb shell work, it just hang there with no output.

**Comment by ngoquang2708** [comment]
Sorry. It work now. I have no idea why!

**Comment by koquantam** [comment]
How???? I encountered this error too.
The only thing i could do when this phone in CM11 is adb shell. No idea why adb logcat doesn't work (showing blinking cursor)

**Comment by ngoquang2708** [comment]
It does not work with that prebuilt kernel. You have to enable the kernel build config to build from source. But there is a problem in the mali gpu driver source. I am fixing it. Here my config:

# kernel
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_PAGESIZE := 2048
TARGET_KERNEL_CONFIG := vivalto3g-native_hw04_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/vivalto3gvn
#TARGET_PREBUILT_KERNEL := device/samsung/vivalto3gvn/prebuilt/kernel

Remember to setup the kernel source code correctly before building.

**Comment by koquantam** [comment]
So does it boots?

**Comment by ngoquang2708** [comment]
No. There is some problems in the proprietary-files.txt that cause surfaceflinger to crash. You have to remove those libraries

lib/libEGL.so
lib/libETC1.so
lib/libGLES_trace.so
lib/libGLESv1_CM.so
lib/libGLESv2.so
lib/libGLESv3.so
lib/libOpenMAXAL.so
lib/libOpenSLES.so

**Comment by koquantam** [comment]
Okay, please add pull requests to me, i'll handle it

**Comment by ngoquang2708** [comment]
OK
