### ISSUE TITLE
Video (en)decoding

### ISSUE THREAD

**Issue by koquantam** [koquantam/android_device_samsung_vivalto3gvn#10]
Chrome FC when going to play a video on YouTube

**Comment by ngoquang2708** [comment]
VLC can play mp4 files but the build in player is not. So does YouTube too.

**Comment by ngoquang2708** [comment]
When using hw decoding, I get this:

I/SprdOMXPlugin(  129): makeComponentInstance 'OMX.sprd.h264.decoder'
I/SPRDAVCDecoder(  129): Construct SPRDAVCDecoder, this: b85a7110
I/SPRDAVCDecoder(  129): SPRDAVCDecoder, video_cfg: 0
I/SPRDAVCDecoder(  129): openDecoder, lib: libomx_avcdec_hw_sprd.so
I/SPRDAVCDecoder(  129): SPRDAVCDecoder, is IOMMU enabled: 1
I/SPRDAVCDecoder(  129): pmem 0x20000000 - 0xb29cb000 - 2097152
D/OMXCodec(  129): Successfully allocated OMX node 'OMX.sprd.h264.decoder'
I/OMXCodec(  129): [OMX.sprd.h264.decoder] AVC profile = 66 (Baseline), level = 30
I/SPRDAVCDecoder(  129): internalGetParameter, OMX_IndexParamVideoPortFormat, eColorFormat: 0x15
E/SPRDAVCDecoder(  129): Failed to open /sys/devices/platform/scxx30-dmcfreq.0/devfreq/scxx30-dmcfreq.0/ondemand/set_freq
I/OMXCodec(  129): [OMX.sprd.h264.decoder] video dimensions are 640 x 360
I/OMXCodec(  129): [OMX.sprd.h264.decoder] Crop rect is 640 x 360 @ (0, 0)
I/SPRDAVCDecoder(  129): internalSetParameter, enable AndroidNativeBuffer
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocating 8 buffers of size 131072 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c01b8 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c0380 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c0450 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c0520 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c05f0 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c0288 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c0850 on input port
I/OMXCodec(  129): [OMX.sprd.h264.decoder] allocated buffer 0xb85c0908 on input port
I/SPRDAVCDecoder(  129): internalGetParameter, OMX_IndexParamGetAndroidNativeBuffer 33
W/GraphicBufferAllocator(  125): alloc(640, 360, 21, 00002933, ...) failed -22 (Invalid argument)
E/        (  125): GraphicBufferAlloc::createGraphicBuffer(w=640, h=360) failed (Invalid argument), handle=0x0
E/BufferQueue(  125): [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
E/OMXCodec(  129): dequeueBuffer failed: Invalid argument (22)
E/OMXCodec(  129): [OMX.sprd.h264.decoder] Allocate Buffer failed - error = -22
E/OMXCodec(  129): [OMX.sprd.h264.decoder] init failed: -22
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c0908 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c0850 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c0288 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c05f0 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c0520 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c0450 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c0380 successful
I/OMXNodeInstance(  129): OMX_FreeBuffer for buffer header 0xb85c01b8 successful
E/AwesomePlayer(  129): failed to start video source
I/SPRDAVCDecoder(  129): Destruct SPRDAVCDecoder, this: b85a7110
E/SPRDAVCDecoder(  129): Failed to open /sys/devices/platform/scxx30-dmcfreq.0/devfreq/scxx30-dmcfreq.0/ondemand/set_freq
I/ActivityManager(  543): Displayed com.android.gallery3d/.app.MovieActivity: +1s361ms
I/Timeline(  543): Timeline: Activity_windows_visible id: ActivityRecord{41b6b170 u0 com.android.gallery3d/.app.MovieActivity t4} time:313584
D/LIGHTS  (  543): file:device/samsung/vivalto3gvn/libs/liblights/lights.c, func:set_light_buttons, on=0
E/MediaPlayer( 1751): error (1, -22)
E/MediaPlayer( 1751): Error (1,-22)
D/CodeauroraVideoView( 1751): Error: 1,-22
I/SPRDHWComposer(  125): Do not support display type: 0
D/ENGPC   (  144): parse_event: event { 'change', '/devices/platform/sec-battery/power_supply/battery', 'power_supply', '' }
I/SPRDHWComposer(  125): Do not support display type: 0
I/SPRDHWComposer(  125): Do not support display type: 0
I/SPRDHWComposer(  125): Do not support display type: 0
I/SPRDHWComposer(  125): Do not support display type: 0
I/SPRDHWComposer(  125): Do not support display type: 0
I/SPRDHWComposer(  125): Do not support display type: 0

**Comment by ngoquang2708** [comment]
It is failed at this step:
```
W/GraphicBufferAllocator(  125): alloc(640, 360, 21, 00002933, ...) failed -22 (Invalid argument)
```

**Comment by koquantam** [comment]
Does video player FC? I got that too

**Comment by koquantam** [comment]
Well, our stock is completely damn broken. It continuously spamming logcat, espically MTP, so i can't see anything much to compare

**Comment by ngoquang2708** [comment]
Everything is working fine (but S/W decoding, of course) except video player.

**Comment by ngoquang2708** [comment]
Some app have its display overflow the screen. Adding density prop = 240 fix that for AOSP Keyboard. But google voice search still got that bug.

**Comment by koquantam** [comment]
Hmm... you tried gapps already? I haven't, because it's very laggy so nano gapps is my best choice
S/W decoding works, but it's damn slow (pictures showing slowish, like 8 yrs old bride :D), even MX Player can't doing better. Maybe Sammy has done sth to libstagefrighthw so its size is bigger than us

**Comment by koquantam** [comment]
What..... mali.ko is over 225kb?
Why i got it over 4mb?

**Comment by ngoquang2708** [comment]
Maybe that is a un-stripped version. Mine is stripped out debug symbols, because it is in kernel source tree so I think that CM does that automatically.

**Comment by ngoquang2708** [comment]
You use nano, I use pico :)

**Comment by ngoquang2708** [comment]
yeah, that true, our libstagefrighthw do not work as we intended. The true fact is, it does not work at all because it does not have ```createOMXPlugin``` function. I just copy it from stock for testing.

**Comment by koquantam** [comment]
So that means you don't have mali in /sys/kernel/debug

**Comment by ngoquang2708** [comment]
Just checked. It is there.

**Comment by koquantam** [comment]
Did you just reserved-engineering the libstagefrighthw?

**Comment by ngoquang2708** [comment]
I ```grep``` .so binary :D

**Comment by koquantam** [comment]
Well that's a good trick

**Comment by ngoquang2708** [comment]
Reserved-engineering is out of my knowledge :)

**Comment by ngoquang2708** [comment]
I look at the code that load libstagefrighthw.so, and it manage to call that function, our does not have that, and SS blob does have that.

**Comment by koquantam** [comment]
Hmm... I tried your recent build and this thing seems working fine, but it currently doesn't support 480p on YouTube

**Comment by ngoquang2708** [comment]
What? On browser or on YT app?

**Comment by koquantam** [comment]
YouTube app. It doesn't FC like before. Haven't tried video playback on FB yet

**Comment by ngoquang2708** [comment]
I never get YouTube app to work.

**Comment by koquantam** [comment]
Video playback on FB doesn't work. Only sounds, no image

**Comment by ngoquang2708** [comment]
YouTube app can play low res video because it use S/W decoding, and S/W decoding have max res of 320/240. So, I need to use H/W decoding to play higher res video, and it fail. So H/W decoding is still not working now.

**Comment by koquantam** [comment]
Yeah, i saw logcat. Needs to get more sources :D

**Comment by koquantam** [comment]
media_codecs.xml?

**Comment by koquantam** [comment]
There's a bunch of changes that we've missed from them. Check sprd_frameworks_av history

**Comment by koquantam** [comment]
Our stock libstagefrighthw works fine, but somehow it got slowish (even in stock, it still slow like that, but will get fast immediately)

**Comment by ngoquang2708** [comment]
Could it play 480p ot higher res?

**Comment by koquantam** [comment]
In MX Player only, other apps FC

**Comment by ngoquang2708** [comment]
I think mx is using its own s/w decoding, just like vlc does, not use h/w.

**Comment by koquantam** [comment]
Oh, i'm wrong again :(

**Comment by koquantam** [comment]
But, in VLC, when using full acceleration, it just acting slowish like that

**Comment by koquantam** [comment]
In the other words: it lags

**Comment by ngoquang2708** [comment]
That true. So, to confirm that whether h/w decoding is working or not, use
YouTube app.

**Comment by koquantam** [comment]
In stock, it could locate the hw en/decoding libs, but in CM it doesn't

**Comment by koquantam** [comment]
I've read somewhere that only 4.4.2 got 480p decoding. Gotta check it out and reports

**Comment by ngoquang2708** [comment]
We are 4.4.4!??

**Comment by koquantam** [comment]
Nah, they said just change android version to 4.4.2, LOL

**Comment by ngoquang2708** [comment]
??? Where are those info?

**Comment by koquantam** [comment]
https://forums.oneplus.net/threads/guide-how-to-enable-1080p-youtube-on-all-1080p-android-devices.86854/

**Comment by ngoquang2708** [comment]
Did you test it?

**Comment by koquantam** [comment]
Yeah, already tested and same results, no changes
I bet they just kidding around everyone :D

**Comment by ngoquang2708** [comment]
:D

**Comment by koquantam** [comment]
Hmm... why stock doesn't have this?
E/SPRDAVCDecoder(  129): Failed to open /sys/devices/platform/scxx30-dmcfreq.0/devfreq/scxx30-dmcfreq.0/ondemand/set_freq
Both compiled and stock kernel don't. Probably Sammy has done sth with it

**Comment by ngoquang2708** [comment]
The phone is randomly dead with no reason, do you encountered it?

**Comment by koquantam** [comment]
If with camera then yes, if it is soft-rebooted then IDK, probably system_server crashed

**Comment by koquantam** [comment]
Now i can confirm that the phone just dead with no reason

**Comment by ngoquang2708** [comment]
Maybe cpu freq in power_config.xml cause this, I make a update, compiling it.

**Comment by koquantam** [comment]
cpu-active is too damn slow. Maybe that's the reason

**Comment by ngoquang2708** [comment]
But that came from stock, sigh, stock again

**Comment by koquantam** [comment]
It dead after pressing power button (fully slept?)

**Comment by ngoquang2708** [comment]
cpu.active is used to mesure power comsumtion, cpu.speeds is the one that get interested

**Comment by ngoquang2708** [comment]
Investigating...

**Comment by koquantam** [comment]
You know what, stock has DVFS, which use to lock the CPU speeds itself, so they could kidding around the frameworks

**Comment by ngoquang2708** [comment]
Likes the battery capacity :D

**Comment by koquantam** [comment]
Yeah :D
Like, a core prime has 2000, but by some magic, it has increased to 2500, LOL

**Comment by ngoquang2708** [comment]
Stock have this too, man:
```
E/SPRDAVCDecoder(  137): Failed to open /sys/devices/platform/scxx30-dmcfreq.0/devfreq/scxx30-dmcfreq.0/ondemand/set_freq
```

**Comment by koquantam** [comment]
Well, good logcat digging
I'm still finding a way to fix this w/o stock blobs

**Comment by koquantam** [comment]
IDK why Spreadtrum includes both HW and SW decoder/encoder
Going to remove SW decoder to see if it works

**Comment by koquantam** [comment]
Hah, got the real problem now
/etc is not being symlink'ed properly. If you do ls /etc, you only see "/etc" only instead of files in /system/etc. Because of that, media_config.xml and media_codecs.xml is not found.

**Comment by ngoquang2708** [comment]
when use CM file manager and browse to /etc, it jumps to /system/etc/
instead of /etc

**Comment by koquantam** [comment]
Well, that's CM FM
For terminal emulator and adb shell, it doesn't

**Comment by ngoquang2708** [comment]
But MediaCodeList.CPP still print the correct list of sped code!

**Comment by koquantam** [comment]
Well, idk then

**Comment by ngoquang2708** [comment]
Confirmed.

**Comment by koquantam** [comment]
Well, i think we should copy it to root folder

**Comment by koquantam** [comment]
Hmm... you mean this above?
`MediaCodecList::MediaCodecList()
    : mInitCheck(NO_INIT) {
    FILE *file = fopen("/system/etc/media_codecs.xml", "r");`

**Comment by ngoquang2708** [comment]
That it. Try ```ls /etc/``` (with trailing ```/``` :)

**Comment by koquantam** [comment]
LOL, you're kidding me :D
CHANGELOG-CM.txt not found

**Comment by ngoquang2708** [comment]
Without /, I see nothing, with / I see a bunch of things, did not notice
that.

**Comment by ngoquang2708** [comment]
Well, it have changlog

**Comment by ngoquang2708** [comment]
Weird things is happening.

**Comment by koquantam** [comment]
Well, i thought just types all of them, you should see it

**Comment by koquantam** [comment]
OK, this damn thing is getting me interested in. Logcat:
I/SprdOMXPlugin(  134): makeComponentInstance 'OMX.sprd.h264.decoder'
I/SPRDAVCDecoder(  134): Construct SPRDAVCDecoder, this: b71b8d08
I/SPRDAVCDecoder(  134): SPRDAVCDecoder, video_cfg: 0
I/SPRDAVCDecoder(  134): openDecoder, lib: libomx_avcdec_hw_sprd.so
I/SPRDAVCDecoder(  134): SPRDAVCDecoder, is IOMMU enabled: 1
I/SPRDAVCDecoder(  134): pmem 0x20200000 - 0xb1f68000 - 2097152
D/OMXCodec(  134): Successfully allocated OMX node 'OMX.sprd.h264.decoder'
I/OMXCodec(  134): [OMX.sprd.h264.decoder] AVC profile = 100 (High), level = 31
I/SPRDAVCDecoder(  134): internalGetParameter, OMX_IndexParamVideoPortFormat, eColorFormat: 0x15
E/SPRDAVCDecoder(  134): Failed to open /sys/devices/platform/scxx30-dmcfreq.0/devfreq/scxx30-dmcfreq.0/ondemand/set_freq
I/OMXCodec(  134): [OMX.sprd.h264.decoder] video dimensions are 1280 x 720
I/OMXCodec(  134): [OMX.sprd.h264.decoder] Crop rect is 1280 x 720 @ (0, 0)
I/SPRDAVCDecoder(  134): internalSetParameter, enable AndroidNativeBuffer
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocating 8 buffers of size 393216 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9938 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9b00 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9bd0 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9ca0 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9d70 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9a08 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71b9fd0 on input port
I/OMXCodec(  134): [OMX.sprd.h264.decoder] allocated buffer 0xb71ba088 on input port
I/SPRDAVCDecoder(  134): internalGetParameter, OMX_IndexParamGetAndroidNativeBuffer 33
W/GraphicBufferAllocator(  129): alloc(1280, 720, 21, 00002933, ...) failed -22 (Invalid argument)
E/        (  129): GraphicBufferAlloc::createGraphicBuffer(w=1280, h=720) failed (Invalid argument), handle=0x0
E/BufferQueue(  129): [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
E/OMXCodec(  134): dequeueBuffer failed: Invalid argument (22)
E/OMXCodec(  134): [OMX.sprd.h264.decoder] Allocate Buffer failed - error = -22
E/OMXCodec(  134): [OMX.sprd.h264.decoder] init failed: -22
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71ba088 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9fd0 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9a08 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9d70 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9ca0 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9bd0 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9b00 successful
I/OMXNodeInstance(  134): OMX_FreeBuffer for buffer header 0xb71b9938 successful
What the damn hell is that invalid argument?

**Comment by koquantam** [comment]
Well, this thing makes us derp like RIL btw

**Comment by ngoquang2708** [comment]
Haha, I make it works now. Doing some test.

**Comment by koquantam** [comment]
What the f*ck?
How???

**Comment by koquantam** [comment]
Or it just SW codecs?

**Comment by ngoquang2708** [comment]
Well, Sammy do some tricks with their code. Apply this patch: (framework_native.diff)[https://gist.github.com/ngoquang2708/2d2779573f3ea6b1b1eb]

**Comment by koquantam** [comment]
Oh, damn
I just got it for now, 1hr ago :D

**Comment by koquantam** [comment]
Still in compiling process

**Comment by ngoquang2708** [comment]
You can lunch then. CD to that dir, then mm.

**Comment by koquantam** [comment]
I use brunch instead. eng build takes pretty longer time than userdebug
I wish i had an SSD :D

**Comment by ngoquang2708** [comment]
I created a simple 
[gralloc.zip](https://github.com/koquantam/android_device_samsung_vivalto3gvn/files/120153/gralloc.zip) to check for supported pixel format and found that gralloc.scx15 does not support pixel format 0x15. So I guess that Sammy do some tricks there, because they have the same logcat like us.

**Comment by ngoquang2708** [comment]
Now fixing the weird colour of the video produced by the camcorder.

**Comment by koquantam** [comment]
Well, you can modify it
Sammy used HW sources from FF OS source in vendor/sprd/open-source
I've checked, there're bunches of libs there, including camera and else.

**Comment by koquantam** [comment]
The real libstagefrighthw use gralloc too

**Comment by ngoquang2708** [comment]
Can you give me the link?

**Comment by koquantam** [comment]
https://git.mozilla.org/?a=project_list;pf=external/sprd-aosp/vendor/sprd

**Comment by ngoquang2708** [comment]
At least h263 doesn't dead with me, haha

**Comment by ngoquang2708** [comment]
How long does take to download that repo with 32Kbps!!!!!!!!!

**Comment by koquantam** [comment]
Wtf?
Well, it's 100mb only and takes 1min with me (10mbps)

**Comment by koquantam** [comment]
You use MIMAX?

**Comment by ngoquang2708** [comment]
True :)

**Comment by koquantam** [comment]
CONFIRMED WORKING!

**Comment by koquantam** [comment]
But... weird things happen
YouTube still only shows 360p instead of 480p like stock

**Comment by ngoquang2708** [comment]
Open new issue, bro.

**Comment by koquantam** [comment]
Ok, no need
We still can play 720p videos. Latest YT seems broken

**Comment by ngoquang2708** [comment]
We needs to change something in init.scx15.rc for h/w to be able to change CPU freq governor.

**Comment by koquantam** [comment]
write 46600 > /sys/devices/platform/scxx30.devfreq.....
That exist in vendor init.scx15.rc

**Comment by ngoquang2708** [comment]
They change permission of set_freq node to system user. But I do not know
why that perms does not persist.

**Comment by koquantam** [comment]
OK, leaves that later
Now i have weird thing to tell
That tutorial from OnePlus forum actually works. It shows 480p now LOL
Why Google? Why?

**Comment by ngoquang2708** [comment]
That why stock can play 480p

**Comment by ngoquang2708** [comment]
It is sadly that I cannot use YT right now :(

**Comment by koquantam** [comment]
Fk you Sammy
But, Core Prime could play at 480p too LOL

**Comment by koquantam** [comment]
YT videos at 480p seems unstable. Lags everywhere
