### ISSUE TITLE
No WiFi direct

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#11]

**Comment by koquantam** [comment]
There's no wifidirect.apk in /system/app so no wifi direct

**Comment by ngoquang2708** [comment]
Yes. Did note it here for later.

**Comment by ngoquang2708** [comment]
I can pair wifi direct with other device, but I can not send anything because sento menu do not have wifi direct, maybe 3rd app can help.

**Comment by koquantam** [comment]
Really? Which in Settings?

**Comment by koquantam** [comment]
Really? Which in Settings?

**Comment by ngoquang2708** [comment]
Go to Wifi settings, touch [...] button

**Comment by ngoquang2708** [comment]
And there you go, Wi-Fi Direct menu shows up

**Comment by koquantam** [comment]
Nah, doesn't exist

**Comment by ngoquang2708** [comment]
I added wifi direct xml with this commit 12a6dad2b82b5858fd064a3ac6b0347e1ab746f8

**Comment by ngoquang2708** [comment]
Check your /system/etc/to/permissions/ to see if wifi.direct.xml is there, if not, copy it to there.

**Comment by koquantam** [comment]
OK, i'll do it later

**Comment by ngoquang2708** [comment]
Note: do not add ```<bool translatable="false" name="config_wifi_p2p_support">true</bool>``` to ```config.xml```, it is unsupported option, I removed with the later commit though.

**Comment by ngoquang2708** [comment]
Please check this.

**Comment by koquantam** [comment]
Confirmed
It appears now, but i don't have a device to check
