### ISSUE TITLE
GPS not work properly

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#12]

**Comment by ngoquang2708** [comment]
GPS is now working probably with pull request #14 . So close this issue.

**Comment by koquantam** [comment]
More works to get done :)
Now the only think we need to fix is RIL and bluetooth.

**Comment by koquantam** [comment]
Hmm... GPS doesn't work at all
It just turns on, cLock (CM clock widget) can't get location

**Comment by ngoquang2708** [comment]
IDK, I can use it, GMaps works with it.

**Comment by koquantam** [comment]
Weird. Can you test it with cLock?

**Comment by ngoquang2708** [comment]
It works for me now. Try remove it. Then re-add it, when reset it, it will show options to enable weather, chose source as OpenWeatherMap, then tick the accept mark, wait for a couple of minutes.

**Comment by koquantam** [comment]
It doesn't work out

**Comment by ngoquang2708** [comment]
Did I make some other derp actions to make it works, like audio rec :D

**Comment by koquantam** [comment]
Well, i'm the one who got derp now LOL

**Comment by koquantam** [comment]
Somehow it actually works now LOL
