### ISSUE TITLE
hwcomposer (maybe a fix in patches)

### ISSUE THREAD

**Issue by koquantam** [koquantam/android_device_samsung_vivalto3gvn#13]
There's a hwcomposer in patches/frameworks/native
Should we try that patch?

**Comment by ngoquang2708** [comment]
Let's try it to see what it does.

**Comment by koquantam** [comment]
Make a backup first (to prevent repo sync again)

**Comment by ngoquang2708** [comment]
Yeah

**Comment by koquantam** [comment]
Any difference? I just got lost power recently

**Comment by koquantam** [comment]
Any ideas about this/
E/HAL     (  121): load: module=/system/lib/hw/hwcomposer.scx15.so
E/HAL     (  121): dlopen failed: cannot locate symbol "_ZN7android13MemoryHeapIon21Get_phy_addr_from_ionEiPiS1_" referenced by "hwcomposer.scx15.so"...
E/SurfaceFlinger(  121): hwcomposer module not found

**Comment by ngoquang2708** [comment]
Like I mentioned before, libbinder in frameworks/native/libs/binder lacks the symbol for hwc.scx15. The libbinder.so blob from stock rom does have that symbol. But when copy it to the phone, it make the phone unstable.

**Comment by koquantam** [comment]
What do you mean "unstable"?

**Comment by ngoquang2708** [comment]
It spam logcat whit unknown events and other things that I don't remember. You could experience it yourself.

**Comment by koquantam** [comment]
like "Enable myanmar Zawgyi converter"?
Stock shows that a lot

**Comment by ngoquang2708** [comment]
I don't remember clearly, some things like E/SPRDHwcomposer ....

**Comment by koquantam** [comment]
Alright replaced stock libbinder.so and it shows a bunch of this:
I/Netd    (  287): Netd 1.0 starting

**Comment by ngoquang2708** [comment]
I searched google and found no result of Get_phy_addr_from_ion. I think that is samsung private code.

**Comment by koquantam** [comment]
LOL, a bunch of:
E/SPRDHWComposer( 439): unsupported event

**Comment by ngoquang2708** [comment]
That it!

**Comment by ngoquang2708** [comment]
MemoryHeapBase::getSize() may be this is our Get_phy_addr_from_ion ????

**Comment by ngoquang2708** [comment]
or this uint32_t MemoryHeapBase::getOffset() ???

**Comment by koquantam** [comment]
I'm searching for in from Spreadtrum sources

**Comment by ngoquang2708** [comment]
OMG, C++. Why?

**Comment by koquantam** [comment]
We need a patch to libbinder so get hwc working

**Comment by ngoquang2708** [comment]
No HWC source code, that is a very hard work to do. My priority now is focused to RIL so at least I dont have to restore to stock rom to make a phone call!!!

**Comment by koquantam** [comment]
Well at least i've found this:
https://git.mozilla.org/?pf=external/sprd-aosp
Maybe there's sth related to out device

**Comment by ngoquang2708** [comment]
FirefoxOS is dead, and those sources is gone too, soo sad.

**Comment by koquantam** [comment]
Oh yeah, just found sth
Anyway, mint got a libbinder fix and got hwc working. I'm asking for the dev to post his patches

**Comment by koquantam** [comment]
Alright, we got the patches here, for libbinder (not a diff patch, just copy-paste to source)
https://github.com/TeamButter/patches?files=1
Gotta get some sleeps now :)

**Comment by ngoquang2708** [comment]
Oh yeahhhhhhhhhhhhhhhhhhhh

**Comment by koquantam** [comment]
Still doesn't work, shows a lot unsupported event in logcat

**Comment by ngoquang2708** [comment]
I think it need some modification in the Android.mk makefile

$(TARGET_OUT_INTERMEDIATES)/KERNEL/

on my system is 

$(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/

Yours?

**Comment by ngoquang2708** [comment]
Please folk my android_frameworks_native, hardware_libhardware, hardware_libhardware_legacy to sync our works.

**Comment by koquantam** [comment]
$(TARGET_OUT)INTERMEDIATES)/KERNEL_OBJ/

**Comment by ngoquang2708** [comment]
in folder out/target/product/vivalto3gvn/obj. there is no KERNEL folder. but KERNEL_OBJ. and libbinder Android.mk use KERNel. please check

**Comment by koquantam** [comment]
Oh yeah, that's real
Gotta change it to see any differences

**Comment by koquantam** [comment]
Nothing changed, still get spamming logcat

**Comment by ngoquang2708** [comment]
Does hwc complain about libbinder any more?

**Comment by koquantam** [comment]
Like what i said, it keep spamming logcat

**Comment by koquantam** [comment]
I got an idea
Try building these blobs with the ROM (not using vendor anymore) and test if it works. They're buildable, i've built this before

**Comment by ngoquang2708** [comment]
but where do you get those sources?

**Comment by koquantam** [comment]
IDK, just add it to device.mk, it will build.

**Comment by ngoquang2708** [comment]
I see. It will not build anything and just ignore it.

**Comment by ngoquang2708** [comment]
Please fork my system_core for libion fix. Then you can verify hwc is now working, and close this issue.

**Comment by koquantam** [comment]
OK, will test it

**Comment by ngoquang2708** [comment]
Oh man. You fork a wrong one. Sorry if confused you but the right one is android_system_core

**Comment by ngoquang2708** [comment]
I fork android_system_core and fix it libion base on libion of sprd_system_core

**Comment by koquantam** [comment]
LOL, still get spamming logcat
Could you tell me how to fix that again?

**Comment by ngoquang2708** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<manifest>

	<remove-project name="CyanogenMod/android_frameworks_native" />
	<project path="frameworks/native" name="koquantam/android_frameworks_native" remote="github" revision="cm-11.0"/>

	<remove-project name="CyanogenMod/android_hardware_libhardware" />
	<project path="hardware/libhardware" name="koquantam/android_hardware_libhardware" remote="github" revision="cm-11.0"/>

	<remove-project name="CyanogenMod/android_hardware_libhardware_legacy" />
	<project path="hardware/libhardware_legacy" name="koquantam/android_hardware_libhardware_legacy" remote="github" revision="cm-11.0"/>

	<remove-project name="CyanogenMod/android_system_core" />
	<project path="system/core" name="koquantam/android_system_core" remote="github" revision="cm-11.0"/>

</manifest>

**Comment by ngoquang2708** [comment]
Download this https://gist.github.com/ngoquang2708/949ca992316c4b132b94
COpy and past it to your cm11-0/.repo/local_manifests/
Delete framewords/native, hardware/libhadrware, hardware/libharware_legacy, system/core
Then repo sync
THen compile

**Comment by koquantam** [comment]
OK, will try

**Comment by koquantam** [comment]
Got this:
https://pastee.org/xbe6j

**Comment by ngoquang2708** [comment]
repo sync --force-sync hardware/libhardware

if faced it again, then force sync again, 4 times at most :D

**Comment by koquantam** [comment]
I use repo sync --force-sync
It has no syntax behind, so use that once :)

**Comment by ngoquang2708** [comment]
I copy that from your pastes though

**Comment by koquantam** [comment]
So, now does it smooth? ex: swiping notification bar?

**Comment by ngoquang2708** [comment]
I now use HWC so yes

**Comment by koquantam** [comment]
GPS doesn't work properly on Quick Settings Bar (only have two options: Off and Device only)

**Comment by koquantam** [comment]
Now let's focus on RIL. This ROM is almost good for daily use.

**Comment by ngoquang2708** [comment]
Device only is GPS.

RIL is now work with just one SIM. But because of audio recoding problem, we cannot make a outgoing call. What make me confuse is that why we can receive a call?

**Comment by koquantam** [comment]
It doesn't work, it shows this in logcat (and stuck on Samsung logo)
https://pastee.org/2mf4y

**Comment by ngoquang2708** [comment]
Check your out/target/product/vivalto3gvn/obj/KERNEL_OBJ/usr/include/linux/ion.h file to see if it have ION_IOC_INVALIDATE definition

**Comment by ngoquang2708** [comment]
Here my build so you can check out http://qrpi.noip.me:10080/upload/cm-11-20160110-UNOFFICIAL-vivalto3gvn.zip

**Comment by koquantam** [comment]
it's defined

**Comment by ngoquang2708** [comment]
Does system/core/libion/Android.mk look like this

LOCAL_PATH:= $(call my-dir)
 
 include $(CLEAR_VARS)
LOCAL_C_INCLUDES += \
    $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include/
 LOCAL_SRC_FILES := ion.c
 LOCAL_MODULE := libion
 LOCAL_MODULE_TAGS := optional
@@ -8,6 +10,8 @@ LOCAL_SHARED_LIBRARIES := liblog
 include $(BUILD_SHARED_LIBRARY)
 
 include $(CLEAR_VARS)
LOCAL_C_INCLUDES += \
    $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include/
 LOCAL_SRC_FILES := ion.c ion_test.c
 LOCAL_MODULE := iontest
 LOCAL_MODULE_TAGS := optional tests

**Comment by koquantam** [comment]
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_C_INCLUDES += \
    $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include/
LOCAL_SRC_FILES := ion.c
LOCAL_MODULE := libion
LOCAL_MODULE_TAGS := optional
LOCAL_SHARED_LIBRARIES := liblog
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_C_INCLUDES += \
    $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include/
LOCAL_SRC_FILES := ion.c ion_test.c
LOCAL_MODULE := iontest
LOCAL_MODULE_TAGS := optional tests
LOCAL_SHARED_LIBRARIES := liblog
include $(BUILD_EXECUTABLE)

**Comment by ngoquang2708** [comment]
F/libc    (  120): Fatal signal 6 (SIGABRT) at 0x00000078 (code=-6), thread 120 (surfaceflinger)
E/SPRDHWComposer(  120): couldn't find an EGLConfig matching the screen format
E/libEGL  (  120): eglGetConfigAttrib(EGL_NATIVE_VISUAL_ID) failed: 0x3001

Check your phone system/lib/egl

**Comment by koquantam** [comment]
It has 4 files like yours

**Comment by koquantam** [comment]
the HWC is partially working, because the launcher is still laggy

**Comment by ngoquang2708** [comment]
May be a clean build will help :D

**Comment by koquantam** [comment]
Man, i've waiting for 3hrs to make a clean build
But i got this in the middle:
system/core/libion/ion.c: In function 'ion_invalidate_fd':
system/core/libion/ion.c:155:26: error: 'ION_IOC_INVALIDATE' undeclared (first use in this function)
system/core/libion/ion.c:155:26: note: each undeclared identifier is reported only once for each function it appears in
system/core/libion/ion.c:156:1: error: control reaches end of non-void function [-Werror=return-type]
cc1: some warnings being treated as errors
make: *** [/home/a1/cm-11.0/out/target/product/vivalto3gvn/obj/EXECUTABLES/iontest_intermediates/ion.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by ngoquang2708** [comment]
This phone spec is not too high, I think that speed is acceptable.

**Comment by koquantam** [comment]
Nope, actually it's 6hrs total (Well, i use ccache so it's decreased half of the time)

**Comment by ngoquang2708** [comment]
My lap just 1.8 GHz. I waited for loooooong

**Comment by koquantam** [comment]
What about that error above?
Did you get that?

**Comment by ngoquang2708** [comment]
I see recently button way more faster than stock

**Comment by ngoquang2708** [comment]
And multitasking is pretty fast

**Comment by ngoquang2708** [comment]
Hey, you don't have a fork of the kernel

**Comment by ngoquang2708** [comment]
Fork mine man

**Comment by koquantam** [comment]
That forked kernel caused error in the middle of the build, so i didn't use it

**Comment by koquantam** [comment]
With mali driver.

**Comment by koquantam** [comment]
Hey, ART is working

**Comment by ngoquang2708** [comment]
God I am missed. I use the original from ss, I guess you just use it like me, forget to push it to github. Sorry.

**Comment by ngoquang2708** [comment]
You mean android runtime?

**Comment by koquantam** [comment]
Yes, it is

**Comment by koquantam** [comment]
But in KitKat, ART is not done yet, so some apps could FC

**Comment by ngoquang2708** [comment]
I will give it a try.

**Comment by ngoquang2708** [comment]
Art is slow for me now

**Comment by koquantam** [comment]
Hey, RIL is not dead
I've changed sth in build.prop and it gets the IMEI on the 2nd SIM

**Comment by ngoquang2708** [comment]
What did you do.

**Comment by koquantam** [comment]
Compare our build.prop with stock, there's sth missing, i added it, but it recognizes IMEI only, not the SIM

**Comment by koquantam** [comment]
And Sth in stock boot.img makes the RIL working. We have to compare it with ours

**Comment by koquantam** [comment]
Inside our init.vivalto3gvn_base.rc, there's 3 ril services, which refers to 3-SIMs not 2, so remove one of them and test it

**Comment by ngoquang2708** [comment]
I found out why libion failed to build. It is because of the kernel is not built yet. The temp workaround now is to build the kernel first. I am finding a way to do automatically.

**Comment by ngoquang2708** [comment]
Did you build the source successfully. And confirm that hwc is working properly so that you should close this issue.

**Comment by koquantam** [comment]
Wanna see this? :D
http://imgur.com/6wGrRJk

**Comment by koquantam** [comment]
Remove ro.opengles.version and ro.kernel.qemu from build.prop to see the magic :D

**Comment by ngoquang2708** [comment]
What the heck? It is super smooth! Why?

**Comment by ngoquang2708** [comment]
And GMaps is now work?

**Comment by koquantam** [comment]
IDK, haven't tried gapps yet
Big thanks to @corphish for this

**Comment by ngoquang2708** [comment]
I have noticed what hwc showing something like: SPRDHWComposer: Unsupported display type 0, now it is gone!

**Comment by ngoquang2708** [comment]
Do you ask him why is that?

**Comment by koquantam** [comment]
Yes, already but haven't got answer yet

**Comment by koquantam** [comment]
I'm digging logcat to find what happens

**Comment by ngoquang2708** [comment]
And camera is working, with stock kernel, damn those props. Where the hell they come from!

**Comment by koquantam** [comment]
At first, logcat doesn't have this
I/SurfaceFlinger(  124): OpenGL ES informations:
I/SurfaceFlinger(  124): vendor    : ARM
I/SurfaceFlinger(  124): renderer  : Mali-400 MP
I/SurfaceFlinger(  124): version   : OpenGL ES 2.0
I/SurfaceFlinger(  124): extensions: GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug 
I/SurfaceFlinger(  124): GL_MAX_TEXTURE_SIZE = 4096
I/SurfaceFlinger(  124): GL_MAX_VIEWPORT_DIMS = 4096
So the problem is wrong GLES version i guess

**Comment by koquantam** [comment]
And the thing you said still exist
I/SPRDHWComposer(  124): Do not support display type: 0

**Comment by koquantam** [comment]
Wait... you said after remove those props, stock kernel camera is working?

**Comment by ngoquang2708** [comment]
May be I closed this issue too soon :)

**Comment by koquantam** [comment]
True true true :D

**Comment by ngoquang2708** [comment]
I am using stock kernel, and after remove those props, CM camera is working.

**Comment by koquantam** [comment]
Hmm... seems like we've to use those stock modules again

**Comment by koquantam** [comment]
And prebuilt stock kernel, too

**Comment by ngoquang2708** [comment]
Wait, I will switch back to our compiled kernel to see if it works.

**Comment by koquantam** [comment]
Nope, i've tried, camera still dead

**Comment by ngoquang2708** [comment]
Damn Sammy again because of that.

**Comment by koquantam** [comment]
Yeah, it's all from Sammy :D

**Comment by ngoquang2708** [comment]
What they gave us if not frustrating?

**Comment by ngoquang2708** [comment]
How do you contact @corphish?

**Comment by koquantam** [comment]
We talk on xda forum
http://forum.xda-developers.com/galaxy-star/orig-development/rom-cyanogenmod-11-18-december-2015-t3273891/post65041358#post65041358

**Comment by ngoquang2708** [comment]
I've to join :D

**Comment by koquantam** [comment]
Yeah, just do it
We'll mention both each other :D

**Comment by ngoquang2708** [comment]
You know, we cannot do anything just our own!

**Comment by ngoquang2708** [comment]
Please re-add ro.opengles.version=131072

**Comment by koquantam** [comment]
Weird things happen
When i switch to CM libbinder, HWC still working (it's being used by OpenGL renderer), cam is gone.
Looks like it only fix the camera

**Comment by ngoquang2708** [comment]
I have no idea, I always use it. And camera BLOB works with it.
