### ISSUE TITLE
Black screen issue on Gmaps and some other apps

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#17]

**Comment by koquantam** [comment]
It's HW issue

**Comment by ngoquang2708** [comment]
Phone apps is flashing black layer when typing numbers.

**Comment by ngoquang2708** [comment]
Yes, notes here for fix in the future.

**Comment by koquantam** [comment]
Yeah. All those abnormal effects are HW issue, because it isn't configured correctly

**Comment by koquantam** [comment]
We need some patches to get HWC fully working. I'm working on it

**Comment by ngoquang2708** [comment]
This is fixed as of eff22a4603eb10ebcebda8f8a441816178f5faf7
