### ISSUE TITLE
Wifi tethering

### ISSUE THREAD

**Issue by koquantam** [koquantam/android_device_samsung_vivalto3gvn#24]
Our libhardware_legacy doesn't have wifi p2p support, so it doesn't work

**Comment by ngoquang2708** [comment]
I guess CM11 is old compare to A4.4

**Comment by ngoquang2708** [comment]
did u try bluetooth telthering

**Comment by koquantam** [comment]
There's no bluetooth tethering

**Comment by ngoquang2708** [comment]
stock have it

**Comment by koquantam** [comment]
Yes, i know, but for our CM11 it doesn't have

**Comment by ngoquang2708** [comment]
so sad

**Comment by koquantam** [comment]
Hmm... maybe missing files, not due to libhardware_legacy

**Comment by ngoquang2708** [comment]
when adding wifi p2p permissions xml. wifi is dead because wpa_supplicant failed to start with p2p support

**Comment by koquantam** [comment]
Bro, after wifi commit, you can confirm wifi tethering is fixed: http://imgur.com/a/2FJWw
And you're right, CM has BT tethering

**Comment by ngoquang2708** [comment]
USB tethering to go

**Comment by koquantam** [comment]
OK man

**Comment by ngoquang2708** [comment]
I cannot use wifi tethering!

**Comment by ngoquang2708** [comment]
It shows a bunch of
```
W/wpa_supplicant( 3820): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant( 3820): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant( 3820): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant( 3820): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant( 3820): p2p-dev-wlan0: Failed to initiate AP scan
```

**Comment by koquantam** [comment]
What?
It's still usable with me

**Comment by koquantam** [comment]
Well, there's no such log like that with me
Have you updated init.wifi.rc?

**Comment by ngoquang2708** [comment]
Yes

**Comment by koquantam** [comment]
OK, i'm out of ideas then

**Comment by ngoquang2708** [comment]
At least bt tethering is working so I just left it here.

**Comment by koquantam** [comment]
Well you've tested BT tethering right?
I don't have a BT tethering compatible device so can't test it now

**Comment by ngoquang2708** [comment]
My laptop have bluetooth. Connected and it can ping google :D

**Comment by koquantam** [comment]
At least VT should costs us about 500d for each pings
