### ISSUE TITLE
USB tethering not work

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#30]

**Comment by koquantam** [comment]
Yeah, i'm finding a workaround for this

**Comment by koquantam** [comment]
I'm finding some positive commits from vivaltonfc3g to get this thing working

**Comment by ngoquang2708** [comment]
This works as of PR #48.

**Comment by koquantam** [comment]
Confirmed

**Comment by koquantam** [comment]
Now i know USB tethering acts like "Network Bridge" in Windows too
It use mobile data and Wifi to get networks connection LOL

**Comment by ngoquang2708** [comment]
Then you have a combo 3G USB dongle and WiFi USB dongle :D
