### ISSUE TITLE
H/W AVC encoding produces wrong image color while using it in video recoding

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#33]
While using camera app to record video, sets codec to h263, mpeg4 produces the correct result. But h264.

**Comment by koquantam** [comment]
How do you record videos?
I'm using cyanogen_vivalto3g_defconfig now and it just freezes the phone, also no logcat when freezes

**Comment by ngoquang2708** [comment]
I think you should make audio recording to work first.

**Comment by ngoquang2708** [comment]
Try to pull my latest update from android_system_core to see if it work.

**Comment by koquantam** [comment]
Well that doesn't too critical, so i'm gonna fix this first

**Comment by ngoquang2708** [comment]
You know, it records audio with video, then...

**Comment by koquantam** [comment]
But mic seems to work fine :D

**Comment by ngoquang2708** [comment]
But you said that you cannot record audio :D, then...

**Comment by ngoquang2708** [comment]
Try delete KERNEL_OBJ and rebuild the kernel to see if it helps. I tried it before and it gave me success.

**Comment by ngoquang2708** [comment]
There is no option to set encoding codec in stock camera!!

**Comment by koquantam** [comment]
Stock is broken, you know

**Comment by ngoquang2708** [comment]
Maybe they can not use avc codec to encode video so they remove those option :D

**Comment by ngoquang2708** [comment]
With new omx codecs, seems this issue is not exists anymore, can you check it?

**Comment by koquantam** [comment]
It was already worked since you switch to stock libstagefrighthw tho

**Comment by ngoquang2708** [comment]
It works, but produces wrong colour. Now it produces the correct one.

**Comment by koquantam** [comment]
Confirmed
