### ISSUE TITLE
Battery never full, stucks at 99%

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#36]

**Comment by koquantam** [comment]
It always full, maybe because of that disabled kernel config before

**Comment by ngoquang2708** [comment]
Maybe this is not CM problem, it still showing 99% in stock rom. Needs battery replacement?!

**Comment by koquantam** [comment]
Or your charger maybe
What do you use to charge the phone? USB or travelling charger

**Comment by ngoquang2708** [comment]
I use travelling charger. I turn the phone off and charge it, now it full.

**Comment by koquantam** [comment]
Hah, very funny now
I got it too :D

**Comment by ngoquang2708** [comment]
Conclusion: BAD BATTERY

**Comment by ngoquang2708** [comment]
So I just leave this issue open unless I buy another new battery!

**Comment by koquantam** [comment]
Damn, CPU-Z shows good battery
Maybe because of the battery config? Because i've replaced with a full s5830i battery but still stucks 99

**Comment by koquantam** [comment]
OR the kernel

**Comment by ngoquang2708** [comment]
I am googling around and see many people complains about this, this is just a common issue of the battery.
Or to be sure, you can switch back to stock an test it.

**Comment by koquantam** [comment]
LOL, it's full now after 5 mins of 99 stuck
So that's your batt is dying

**Comment by ngoquang2708** [comment]
LOL
