### ISSUE TITLE
Camera app crashes if taking photo after switching back from recording mode

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#39]
It can make flash in low light condition, but then it crashes.

**Comment by koquantam** [comment]
Confirmed. I use stock core33g binder to makes this damn thing work
What did you do to the libbinder to makes camera working?

**Comment by ngoquang2708** [comment]
I just use libbinder's patches from @corphish, committed to repo.

**Comment by koquantam** [comment]
This seems doesn't exist now

**Comment by ngoquang2708** [comment]
This still exist with me. It occurs when low light detection not work properly.

**Comment by koquantam** [comment]
Anything from logcat?
