### ISSUE TITLE
Notification drawer shows "NO SERVICE" instead of operator names

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#40]

**Comment by koquantam** [comment]
Well, that's a bug and i've done a workaround with it (already said to you)
Needs init scripts digging to get it working

**Comment by koquantam** [comment]
One more thing: Did you registered SIM cards?

**Comment by ngoquang2708** [comment]
What you mean "registered"?

**Comment by koquantam** [comment]
In Settings >> SIM cards >> Configure SIM cards
You must active first

**Comment by koquantam** [comment]
Not by calling 18001090 :D

**Comment by ngoquang2708** [comment]
Wait, I don't have ```Configure SIM cards``` option?

**Comment by ngoquang2708** [comment]
What will happen if you change those settings?

**Comment by koquantam** [comment]
Well, you could use both SIMs for calls and 1st SIM for mobile data
Maybe you only use one SIM so that setting isn't available

**Comment by ngoquang2708** [comment]
I have 2 sims, and I cannot do anything with sim 2 except make it register to network by using your workaround.

**Comment by koquantam** [comment]
Actually, SIM 2 works on first start after factory reset or clean install and registers both SIMs
RIL2 crashes after reboot

**Comment by ngoquang2708** [comment]
This works now.
