### ISSUE TITLE
WHITE home screen search bar when first time install Google Search app

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#43]
Restart solves it.

**Comment by koquantam** [comment]
Well, that's not a big problem if a simple restart solves it

**Comment by ngoquang2708** [comment]
Need to find the cause.

**Comment by ngoquang2708** [comment]
Did you notice this, Gmaps app is not as smooth as on stock ROM.

**Comment by koquantam** [comment]
If it was newest gg maps then it lags like hell. IDK why but even a GS2 lags when using it
