### ISSUE TITLE
AnTuTu Benchmark shows unsupported 3D

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#44]

**Comment by koquantam** [comment]
Even stock has that, man
Our graphics is very poor. Asphalt 8 lags then don't say 3D

**Comment by ngoquang2708** [comment]
Didn't notice this in stock ROM.

**Comment by koquantam** [comment]
Well, mint users usually complaints about this, too

**Comment by ngoquang2708** [comment]
@corphish said on xda that this is dalvik bug but didn't say details. Waiting for his fix.

**Comment by koquantam** [comment]
Well, he just told that he changed dalvik.vm.heapsize and heapstartsize to fix

**Comment by koquantam** [comment]
To correct with mint's stock
