### ISSUE TITLE
Not an issue, just CM12.1 discussion

### ISSUE THREAD

**Issue by koquantam** [koquantam/android_device_samsung_vivalto3gvn#46]
Leave this closed

**Comment by koquantam** [comment]
It seems that we've to use sth from MTK sources

**Comment by ngoquang2708** [comment]
What are they?

**Comment by koquantam** [comment]
IDK yet, but MTK like us, cortex-A7 and it has CM12.1 already

**Comment by ngoquang2708** [comment]
OK, interesting. Can you give me some links?

**Comment by koquantam** [comment]
This source is for Wiko Rainbow
https://github.com/Al3XKOoL/android_device_wiko_rainbow/tree/cm-12.1

**Comment by koquantam** [comment]
YEAHHHHHHHH!!!!!!!!!!!!1
CM12.1 booted

**Comment by koquantam** [comment]
Will post screenshots :D

**Comment by ngoquang2708** [comment]
Glad to know.

**Comment by koquantam** [comment]
Here dude :D:D:D:D:D
![screenshot_2016-02-07-12-22-49](https://cloud.githubusercontent.com/assets/13411810/12871104/221a79c2-cd9b-11e5-9fd9-b927effec926.png)

**Comment by koquantam** [comment]
It's almost as usable as CM11, but need some config in source to make it fully working as CM11
I forgot the ril-daemon from init.rc so no baseband at that time :D

**Comment by ngoquang2708** [comment]
Good job bro.

**Comment by koquantam** [comment]
Say "Happy new year" this midnight :D

**Comment by ngoquang2708** [comment]
I want to test it bro, link please.

**Comment by koquantam** [comment]
OK, wait a little

**Comment by koquantam** [comment]
10 mins for first start LOL

**Comment by koquantam** [comment]
WTF, mobile data works on SIM 2

**Comment by ngoquang2708** [comment]
At least it starts :D

**Comment by koquantam** [comment]
I've modified RAMDISK a little, so this build you've to do "start sprd-ril-daemon" and "start sprd-ril-daemon2-3" to start 3 RILs daemon (forgot this :D)

**Comment by koquantam** [comment]
https://drive.google.com/file/d/0BzWikRa31-8qS2RBWlI5WmhuSFk/view

**Comment by koquantam** [comment]
Missing terminal emulator, FK
You've to do on terminal adb instead :D

**Comment by ngoquang2708** [comment]
OK

**Comment by koquantam** [comment]
Does it looks well?

**Comment by ngoquang2708** [comment]
First start is very slow. But UI is very smooth!

**Comment by koquantam** [comment]
Yeah, HWC is enabled, but had to add some config to make it work

**Comment by koquantam** [comment]
Alright, i just have pushed working CM12.1 branch

**Comment by koquantam** [comment]
Bro, i'm thinking about de-odexing the ROM

**Comment by koquantam** [comment]
Since people always use xposed, and after installing, it takes lots of time to recompile the apps btw, so no need for odexing anymore

**Comment by ngoquang2708** [comment]
At least, let them boot into the OS quickly to do something.

2016-04-03 7:35 GMT+07:00 Quyền <notifications@github.com>:

**Comment by ngoquang2708** [comment]
And not everyone use Xposed.

2016-04-03 22:09 GMT+07:00 Quang Ngô <ngoquang2708@gmail.com>:
