### ISSUE TITLE
WiFi not work.

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#5]
I open this issue so that all WiFi issues goes here.

**Comment by koquantam** [comment]
Wifi is pretty fast compared with stock

**Comment by ngoquang2708** [comment]
Please commit your change to in wpa config.

**Comment by ngoquang2708** [comment]
I got this in logcat
'''
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
W/wpa_supplicant(  613): p2p-dev-wlan0: Failed to initiate AP scan
'''

Do you have it?

**Comment by koquantam** [comment]
Stock WPA_supplicant does have it
