### ISSUE TITLE
Phone randomly freeze for no reason

### ISSUE THREAD

**Issue by koquantam** [koquantam/android_device_samsung_vivalto3gvn#54]
Logcat is dead when freezes

**Comment by koquantam** [comment]
Confirmed. The overlay commits make the phone freezes immediately

**Comment by koquantam** [comment]
Well, @corphish said this is the binder issue. Going to recompile the original bindet source to see it's true or not

**Comment by ngoquang2708** [comment]
Do not use libbinder blob

**Comment by koquantam** [comment]
I don't use it, and it's freezes like that too

**Comment by ngoquang2708** [comment]
Try disable dual sim, I cannot use dual sim at all.

**Comment by koquantam** [comment]
Nah, it freezes when running intensive apps, like games.

**Comment by ngoquang2708** [comment]
Weird.

**Comment by koquantam** [comment]
Could you try playing Subway Surfers to see if it freezes or not?
Reopen it about 3 times

**Comment by ngoquang2708** [comment]
Currently I don't have a fast internet connection to download that game. I'll try it later.

**Comment by koquantam** [comment]
Any ideas about this:
E/JavaBinder(  534): !!! FAILED BINDER TRANSACTION !!!

**Comment by koquantam** [comment]
What the f*ck is this?

> I/Android ( 1552): ######### 1 #########                                                                            
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 131 #########
I/Android ( 1552): ######### 132 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 121 #########
I/Android ( 1552): ######### 122 #########
I/Android ( 1552): ######### 123 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 131 #########
I/Android ( 1552): ######### 132 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 121 #########
I/Android ( 1552): ######### 122 #########
I/Android ( 1552): ######### 123 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 131 #########
I/Android ( 1552): ######### 132 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 121 #########
I/Android ( 1552): ######### 122 #########
I/Android ( 1552): ######### 123 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 131 #########
I/Android ( 1552): ######### 132 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 121 #########
I/Android ( 1552): ######### 122 #########
I/Android ( 1552): ######### 123 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 131 #########
I/Android ( 1552): ######### 132 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 131 #########
I/Android ( 1552): ######### 132 #########
I/Android ( 1552): ######### 14 #########
I/Android ( 1552): ######### 11 #########
I/Android ( 1552): ######### 12 #########
I/Android ( 1552): ######### 121 #########
I/ActivityManager(  531): Process com.android.providers.calendar (pid 1243) has died.
V/PanelView(  590): animationTick called with dtms=0; nothing to do (h=112.765076 v=-265.64142)
I/ActivityManager(  531): Process com.android.email (pid 1423) has died.
I/ActivityManager(  531): Process org.cyanogenmod.voiceplus (pid 1520) has died.
I/ActivityManager(  531): Process com.android.gallery3d (pid 1505) has died.
I/ActivityManager(  531): Process com.android.calendar (pid 1321) has died.
I/ActivityManager(  531): Process com.cyanogenmod.account (pid 1590) has died.

**Comment by koquantam** [comment]
People confuse a lot about this, so i've to solve it quickly

**Comment by koquantam** [comment]
Confirmed. Kernel issue
