### ISSUE TITLE
Cannot use mp4 encoder with new omx modules

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#61]
Sammy mp4 encoder is a bit old, it does not have some function symbols that is required by omx code. Replace libomx_m4vh263enc_hw_sprd.so with [this](https://github.com/koquantam/android_device_samsung_vivalto3gvn/files/125872/libomx_m4vh263enc_hw_sprd.so.zip) solve this issue.

**Comment by koquantam** [comment]
OK, i'll check

**Comment by ngoquang2708** [comment]
Solved as of #63
