### ISSUE TITLE
cm-11.0: WAV format crashes SoundRecorder

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#66]

**Comment by koquantam** [comment]
I thought AMR was enough :D

**Comment by ngoquang2708** [comment]
In cm12.1, default stagefright media player - NuPlayer - causes this issue too. When switch to AwesomePlayer in DevSettings, every file formats works flawlessly. Can you try this on cm11 because I do not have it to test right now.

**Comment by koquantam** [comment]
CM11 doesn't have NuPlayer tho

**Comment by ngoquang2708** [comment]
Weird. Why cm12.1 AwesomePlayer can record wav, but cm11.0?

**Comment by koquantam** [comment]
Again, this is a common issue on CM11
https://jira.cyanogenmod.org/browse/CYAN-3937
Needs disabling WAV format

**Comment by ngoquang2708** [comment]
I will try to disable it in xml overlay.

**Comment by ngoquang2708** [comment]
Pushed a workaround here d5b5ef1bd3497f60667fb66c2afc6300d8399984.
