### ISSUE TITLE
Too much BASS on back speaker causes cracked sounds

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#69]

**Comment by koquantam** [comment]
It's nature bro, not an issue.

**Comment by ngoquang2708** [comment]
I think there is some config to reduce sound volume or to reduce BASS volume.

**Comment by koquantam** [comment]
It's equalizer bro, in DSP Manager

**Comment by ngoquang2708** [comment]
I enable Equalizer, reduce all columns, problem stills persist.
