### ISSUE TITLE
Bluetooth not work.

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#7]

**Comment by koquantam** [comment]
Got a fix: copy bluetooth firmware to /system/bin

**Comment by koquantam** [comment]
I see there's bluetooth permission and framework in stock

**Comment by ngoquang2708** [comment]
Using just libbt-vendor.so from SS make bluetooth work now!

**Comment by koquantam** [comment]
What??? It does?
Mine got Bluetooth.apk FC. Did you included in the ROM the permissions and frameworks?

**Comment by ngoquang2708** [comment]
done nothing except copy that file from samsung and put it there. reboot.
done.

**Comment by ngoquang2708** [comment]
me just fc like yours before

**Comment by ngoquang2708** [comment]
it likely that we have a misconfig  of libbt

**Comment by koquantam** [comment]
Oh, yeah! Yay! Now let's close this issue

**Comment by ngoquang2708** [comment]
it is good to find out what is Ss way of config libbt.

**Comment by koquantam** [comment]
So that the first time we don't have bt_vendor.conf and it FC

**Comment by ngoquang2708** [comment]
maybe

**Comment by koquantam** [comment]
Well, damn. Installed CM and all of the services are DIED

**Comment by ngoquang2708** [comment]
try comment ril class in build.prop

**Comment by ngoquang2708** [comment]
Or you may regenerate your vendor dir

**Comment by ngoquang2708** [comment]
Or you may make a clean build :)

**Comment by koquantam** [comment]
Well, i found sth interesting in our stock :D
http://imgur.com/a/C4NKG

**Comment by koquantam** [comment]
That was a hidden feature

**Comment by koquantam** [comment]
How did you get BT working? I still get that FC

**Comment by ngoquang2708** [comment]
How could u do that?

**Comment by ngoquang2708** [comment]
Install the ROM from the link I gave u
 Replace libbt-vendor with stock version.

**Comment by koquantam** [comment]
Well, i just placed libart.so, libart-compiler.so, dex2oat, oatdump, core-libart.jar/odex to stock system folder and reboot, WHOA!
But it doesn't usable, because stock is odexed and i'm deodexing it, if not all services are died and ART says missing classes.dex
And BT still FC :D

**Comment by ngoquang2708** [comment]
I will build it later. Busy now.

**Comment by ngoquang2708** [comment]
It is strange, it seems that cm-11 bluedroid version is a bit outdate!!! It does have some function that samsung libbt-vendor.so required. Cm-12.1 does have those function, but I do not know how to update bluedroid in cm-11.0, lots of differences.

**Comment by koquantam** [comment]
Well you have to port it, and it's not easy

**Comment by ngoquang2708** [comment]
One more thing, we need libbt-hci.so from stock to make bluetooth to work. Sorry about the missing.

**Comment by koquantam** [comment]
That's strange. Our phone doesn't have brcm_patchram_plus but Sammy included BT vendor firmware LOL

**Comment by ngoquang2708** [comment]
Where is that ```brcm_patchram_plus```?

**Comment by koquantam** [comment]
From old Sammy phones, such as S5830i
