### ISSUE TITLE
Set data subscription to 1st sim crash modem

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#73]

**Comment by ngoquang2708** [comment]
Crash just happened when turning on mobile data.

**Comment by koquantam** [comment]
Why I don't have it LOL

**Comment by koquantam** [comment]
IDK why these weird problems occurs with you. I haven't got this
Seems your sources being polluted

**Comment by ngoquang2708** [comment]
This is nothing compared to audio blobs, they suppose to be MR0_AUDIO_BLOB, but some how they work without MR0_AUDIO_BLOB, and MR0_AUDIO_BLOB crashes them. Very, very headache.

**Comment by ngoquang2708** [comment]
Fixed by https://github.com/ngoquang2708/android_frameworks_base/commit/1dcc59f9426a9ff8a9a288da3175607d03d1d269.
