### ISSUE TITLE
Camera not work[PARTIALLY FIXED]

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#8]

**Comment by ngoquang2708** [comment]
When using kernel and all *.ko modules compiled from source on stock rom, it can boot normally but something dont work, likes camera... I have no idea.

**Comment by koquantam** [comment]
Yeah, stock kernel causes camera FC
Btw, i'm compiling CM12.1 and got this
--------- beginning of main
I/lowmemorykiller(  115): Using in-kernel low memory killer interface
W/auditd  (  113): type=2000 audit(0.0:1): initialized
I/auditd  (  113): type=1403 audit(0.0:2): policy loaded auid=4294967295 ses=4294967295
W/auditd  (  113): type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
W/init    (   86): type=1400 audit(0.0:4): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (   86): type=1400 audit(0.0:5): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (   86): type=1400 audit(0.0:6): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (   86): type=1400 audit(0.0:7): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (    1): type=1400 audit(0.0:8): avc: denied { setattr } for name="su" dev="mmcblk0p18" ino=1780 scontext=u:r:init:s0 tcontext=u:object_r:su_exec:s0 tclass=file
W/init    (    1): type=1400 audit(0.0:9): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (    1): type=1400 audit(0.0:10): avc: denied { sys_module } for capability=16 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=capability
W/init    (    1): type=1400 audit(0.0:11): avc: denied { setattr } for name="mmcblk0" dev="tmpfs" ino=3687 scontext=u:r:init:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
W/init    (    1): type=1400 audit(0.0:12): avc: denied { setattr } for name="mmcblk0" dev="tmpfs" ino=3687 scontext=u:r:init:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
W/init    (    1): type=1400 audit(0.0:13): avc: denied { getattr } for path="/dev/mem" dev="tmpfs" ino=3472 scontext=u:r:init:s0 tcontext=u:object_r:kmem_device:s0 tclass=chr_file
I/ServiceManager(  116): service 'media.audio_flinger' died
I/ServiceManager(  116): service 'media.audio_flinger' died

**Comment by ngoquang2708** [comment]
There is something to do with selinux enforcing on boot. How to compile kernel with selinux set to permissive?

**Comment by koquantam** [comment]
add androidboot.selinux=permissive to BOARD_KERNEL_CMDLINE

**Comment by ngoquang2708** [comment]
Did you give it a try?

**Comment by koquantam** [comment]
Oh, i forgot. Add it with space, not comma

**Comment by koquantam** [comment]
Yes, i'm going to recompile it

**Comment by ngoquang2708** [comment]
My plans today was compile cm-12.1, you do, too :)

**Comment by koquantam** [comment]
Yeah, i've just started compiling it yesterday. Got 80GB HDD eaten after 8hrs :D

**Comment by ngoquang2708** [comment]
Hey, did you try compiled kernel and *.ko modules ON STOCK rom? I tried, and it gives differences result than stock kernel. Why is that?

**Comment by koquantam** [comment]
IDK. Camera failed in stock too. Maybe Sammy has done sth :)

**Comment by ngoquang2708** [comment]
My 500GiB now left only 50GiB, OMG.

**Comment by ngoquang2708** [comment]
Plan for a 1TiB :)

**Comment by koquantam** [comment]
If you use ccache, it's even bigger, but for faster builds (since ccache'ed files are copied when compiling)

**Comment by ngoquang2708** [comment]
Yeah, that ccache eat my HDD

**Comment by koquantam** [comment]
Well that damn SELinux doesn't change to Permissive on boot

**Comment by ngoquang2708** [comment]
No idea

**Comment by ngoquang2708** [comment]
Compilation stops at: 

target Java: wifi-service (/home/quang/android/cm-12.1/out/target/common/obj/JAVA_LIBRARIES/wifi-service_intermediates/classes)
frameworks/opt/net/wifi/service/java/com/android/server/wifi/WifiController.java:137: error: cannot find symbol
            R.integer.def_wifi_idle_ms);
                     ^
  symbol:   variable def_wifi_idle_ms
  location: class integer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

**Comment by koquantam** [comment]
Check them up, there's sth that the screen  has passed

**Comment by koquantam** [comment]
Wait.... Is that error has red color?

**Comment by ngoquang2708** [comment]
Yes, It does.

**Comment by koquantam** [comment]
Then you need to check that file in CyanogenMod repo, maybe that's incorrect during source download

**Comment by ngoquang2708** [comment]
Found this:

static bool selinux_is_enforcing(void)
{
#ifdef ALLOW_DISABLE_SELINUX
    char tmp[PROP_VALUE_MAX];

    if (property_get("ro.boot.selinux", tmp) == 0) {
        /* Property is not set.  Assume enforcing */
        return true;
    }

    if (strcmp(tmp, "permissive") == 0) {
        /* SELinux is in the kernel, but we've been told to go into permissive mode */
        return false;
    }

    if (strcmp(tmp, "enforcing") != 0) {
        ERROR("SELinux: Unknown value of ro.boot.selinux. Got: \"%s\". Assuming enforcing.\n", tmp);
    }

#endif
    return true;
}

So, add a build prop of ro.boot.selinux=permissive to disable enforcing selinux :), delete old obj/EXECUTABLES/init_...... to have a fresh build.

**Comment by ngoquang2708** [comment]
OK, I ll check it out.

**Comment by koquantam** [comment]
Still doesn't work
Maybe that's not a problem. Now is the dead media.audio_flinger. The phone stuck on Sammy logo

**Comment by ngoquang2708** [comment]
Can I see your logcat?

**Comment by koquantam** [comment]
After that, just only "service 'media.audio_flinger' died" :
a1@desktop:~$ adb logcat
--------- beginning of main
I/lowmemorykiller(    0): Using in-kernel low memory killer interface
W/auditd  (  115): type=2000 audit(0.0:1): initialized
I/auditd  (  115): type=1403 audit(0.0:2): policy loaded auid=4294967295 ses=4294967295
W/auditd  (  115): type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
W/init    (   86): type=1400 audit(0.0:4): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (   86): type=1400 audit(0.0:5): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (   86): type=1400 audit(0.0:6): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (   86): type=1400 audit(0.0:7): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (    1): type=1400 audit(0.0:8): avc: denied { setattr } for name="su" dev="mmcblk0p18" ino=1779 scontext=u:r:init:s0 tcontext=u:object_r:su_exec:s0 tclass=file
W/init    (    1): type=1400 audit(0.0:9): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir
W/init    (    1): type=1400 audit(0.0:10): avc: denied { getattr } for path="/data/local/tmp/slog/slog_sock" dev="mmcblk0p20" ino=47431 scontext=u:r:init:s0 tcontext=u:object_r:shell_data_file:s0 tclass=sock_file
D/NVITEM  (  187): /system/bin/nvitemd /dev/spipe_w1 /system/etc/nvitem_w.cfg FALSE
D/NVITEM  (  187): /system/bin/nvitemd /dev/spipe_w1 /system/etc/nvitem_w.cfg FALSE
D/NVITEM  (  187): is_cali_mode 0 
D/NVITEM  (  187): NVITEM: ramDisk_Init enter
D/NVITEM  (  187): NVITEM:	partId	originImage		backupImage		length
D/NVITEM  (  187): NVITEM:	0x       1	/dev/block/platform/sprd-sdhci.3/by-name/FIXNV1	/dev/block/platform/sprd-sdhci.3/by-name/FIXNV2	0x   40000
D/NVITEM  (  187): NVITEM:	0x       2	/dev/block/platform/sprd-sdhci.3/by-name/RUNTIMENV1	/dev/block/platform/sprd-sdhci.3/by-name/RUNTIMENV2	0x   60000
D/NVITEM  (  187): NVITEM get config finished! 
D/NVITEM  (  187): ramDisk_Read enter
D/NVITEM  (  187): NVITEM partId1:/dev/block/platform/sprd-sdhci.3/by-name/FIXNV2 read success!
D/NVITEM  (  187): ramDisk_Read enter
D/NVITEM  (  187): NVITEM partId2:/dev/block/platform/sprd-sdhci.3/by-name/RUNTIMENV1 read success!
D/NVITEM  (  187): NVITEM:channel open
D/NVITEM  (  187): NVITEM:_getPacket
D/gpsd    (  179): WakeLock(Release,GPSD)
D/gpsd    (  179): WakeLock(Release,SUPL)
D/ATDistributer(  179): [get_agps_cp_interface]: is called
D/ATDistributer(  179): [agps_c_plane_stack_init]: Entry point
D/ATDistributer(  179): open /dev/stty_w21 --> atc0
D/ATDistributer(  179): /dev/stty_w21 is tty device, force it to be raw data mode
D/ATDistributer(  179): [agps_c_plane_stack_init]: Exit point. rc = 0
I/gpsd_d  (  179): GNSS: 206888
I/ServiceManager(  118): service 'media.audio_flinger' died
I/ServiceManager(  118): service 'media.audio_flinger' died
I/ServiceManager(  118): service 'media.audio_flinger' died
I/ServiceManager(  118): service 'media.audio_flinger' died
I/ServiceManager(  118): service 'media.audio_flinger' died
I/ServiceManager(  118): service 'media.audio_flinger' died
I/ServiceManager(  118): service 'media.audio_flinger' died

**Comment by ngoquang2708** [comment]
It seems init cannot access files on system partition due to selinux

**Comment by koquantam** [comment]
If then, why those later services could run?

**Comment by koquantam** [comment]
I think our problem is that dead service

**Comment by ngoquang2708** [comment]
W/init ( 86): type=1400 audit(0.0:7): avc: denied { write } for name="etc" dev="mmcblk0p18" ino=331 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir

**Comment by ngoquang2708** [comment]
Need a permissive kernel right now, bro

**Comment by koquantam** [comment]
Hmm....doing it

**Comment by ngoquang2708** [comment]
My error is due to out of sync :)

**Comment by koquantam** [comment]
Dat damn SELinux needs to be disabled by executing in init scripts

**Comment by koquantam** [comment]
Nah, still exist.

**Comment by ngoquang2708** [comment]
init binary set it my bro, see the code above

**Comment by koquantam** [comment]
Yes, i know, but G313HU done that and success

**Comment by ngoquang2708** [comment]
I will try set ro.boot.selinux=permissive and report the result

**Comment by koquantam** [comment]
No need. I already tried, and getenforce still gets Enforcing

**Comment by ngoquang2708** [comment]
Confirmed.

**Comment by koquantam** [comment]
Going to do a clean build with commented-out hardware things to see any differences
Dat takes 5 of 6GB zRAM (LOOOOL)

**Comment by ngoquang2708** [comment]
You have 16G ram?

**Comment by koquantam** [comment]
Nope, only 4GB man. I don't have that much $$ :D
I set zRAM equals to 3/2 capacity of my RAM, so compiling does not gets "out-of-resource" error.

**Comment by ngoquang2708** [comment]
How to set that such high value, I am install zram-config and it automatically set my zram to about 3.6G (nearly half of my ram)

**Comment by koquantam** [comment]
Wut??? You have 8GB. Well, idk why linux reserves RAM. Maybe for some reasons
To set zRAM value, do
sudo nano /etc/init/zram-config.conf
find mem= , after totalmem, multiple it as you want (3/2 is a good value, but don't set too high, it's wasted zRAM)

**Comment by ngoquang2708** [comment]
Thank you. Sometime, linking libwebviewchromium.so eat my ram up to 7G, just think that 8G is not enough, but 8G is my laptop limit an I cannot effort for another laptop to get 16G :)

**Comment by koquantam** [comment]
Your lap is quad-core right?
If so, that RAM usage isn't fit your build

**Comment by ngoquang2708** [comment]
What do you mean it isn't fit my build?

**Comment by ngoquang2708** [comment]
It processor is an i3 so not really a quad-core

**Comment by ngoquang2708** [comment]
And I think that laptop cpu performance is far behind desktop one

**Comment by koquantam** [comment]
I mean a quad-core computer must have 16GB RAM to build fast and prevent out-of-memory situation. 
You should upgrade if you can :D
An i3 has dual-core, but Intel has Hyper-Threading in their Core i series, so just know that you have a quad-core computer (the real thing that you have 2 physical cores and 2 logical cores), so build gets faster

**Comment by ngoquang2708** [comment]
I understand it now. But 8G is max out of my laptop spec anyway.

**Comment by koquantam** [comment]
Yeah, so zRAM is an alternative way to increase your RAM :D

**Comment by koquantam** [comment]
Even it's a swap device

**Comment by ngoquang2708** [comment]
That is the reason why android use it for low ram device.

**Comment by ngoquang2708** [comment]
Trying disabled selinux in kernel config. Hope that the kernel will work without selinux.

**Comment by koquantam** [comment]
Have you tried it?

**Comment by ngoquang2708** [comment]
Tried. It even cannot mount system.

**Comment by koquantam** [comment]
Yeah, of course, because CM12.1 needs SELinux

**Comment by koquantam** [comment]
remove libtinyalsa.so from cm12.1 proprietary files, because it's built with the ROM

**Comment by koquantam** [comment]
I'll try to update the proprietary files when i found sth

**Comment by koquantam** [comment]
Remove these in CM12.1's proprietary-files.txt
lib/libsonivox.so
lib/libtinyalsa.so
lib/libcutils.so

**Comment by koquantam** [comment]
I think we should pause CM12.1 project, since Spreadtrum doesn't support it anyway

**Comment by ngoquang2708** [comment]
I am currently install cm on sd card to easilly switch between stock and cm. Do you want to participate?

**Comment by koquantam** [comment]
How? UART?

**Comment by ngoquang2708** [comment]
No need. Just prepare a GPT sdcard with a fat partition for sdcard storage, a ext4 partition for system, another ext4 for data, then change mount point in fstab to reflect the layout on sdcard, then flash the boot.img, sync system folder  to the one in sdcard, plugin the phone, boot up and here we go

**Comment by ngoquang2708** [comment]
to switch between two os, we just need to switch the boot.img, pretty simple

**Comment by koquantam** [comment]
Oh, i've done this before...but stuck bootloop. Forgot to change to GPT sdcard. Thanks for advice.

**Comment by ngoquang2708** [comment]
I do not know if GPT helps, just use it for more partitions support ;)

**Comment by koquantam** [comment]
I'll still left default data partition, since i don't do much in stock, just calling. Besides, sdcards' reading speeds is EXTREMELY slow compared to eMMC, so i'll take cache partition as /data and dalvik-cache is in proper partition :D

**Comment by koquantam** [comment]
But... when installing another ROM, we need to mount /system manually in TWRP

**Comment by ngoquang2708** [comment]
No No

**Comment by ngoquang2708** [comment]
updater-script do that automatically so we need to sync file to sdcard manually

**Comment by ngoquang2708** [comment]
or edit contents of updater-script so that it will mount the right partition.

**Comment by ngoquang2708** [comment]
It wipe my stock rom because of that, luckily I had a backup.

**Comment by koquantam** [comment]
Well, stock is damn slow when installing many apps, and it's RAM-eater.
At least now i can easily make calls without another Nokia's brick :D

**Comment by ngoquang2708** [comment]
i ussually make 2 backup of both boot partition. then i restore the one i
want to use. no more flash full rom and make full rom backup

**Comment by ngoquang2708** [comment]
going further. i modify stock boot to mount a partition as data. now my
internal storage is 8g. too much space  for apps :)

**Comment by koquantam** [comment]
Don't use /data partition in the sdcard, because it's EXTREMELY slow (you'll see it on FB, about 2hrs loading with me :( ) and it'll kill your SD easily

**Comment by koquantam** [comment]
It's not fun at all

**Comment by ngoquang2708** [comment]
I do not know, its seems fast to me.

**Comment by koquantam** [comment]
Well that's my opinion, so decide yourself, no one can force you :D
Btw, that damn libstagefrighthw causes EGL_NOT_INITIALIZED again (in logcat)

**Comment by ngoquang2708** [comment]
Oh, I forgot to ask. Where do you found that libstagefrighthw source? I found one but I think mine is not the right one so I decided not to push it here.

**Comment by koquantam** [comment]
Well, i just type "SprdOMXPlugin.h" and found it, since G313HN's source got that, but "BrcmOMXPlugin" so i just referred it and found them in sprd_frameworks_av

**Comment by koquantam** [comment]
But it's deleted from original source

**Comment by ngoquang2708** [comment]
The deleted it, but git has their history. So there we go :)

**Comment by koquantam** [comment]
Yes, and there're lots of things we've missed
Btw, i'm downloading the AOSP 4.4.2 source (damn crazy right? but just testing it with stock, since our stock is AOSP too with some Sammy stuff there and same with Sammy's stock Android version)

**Comment by koquantam** [comment]
And we're already known that FFOS's git just dead at Android 4.4.2 (you'll found it when you see their commits), so it's pretty hard to make them work in CM11 (don't even say that CM's hardware is a bit different than AOSP) and i'm just a noob at C/C++ :D

**Comment by ngoquang2708** [comment]
So do I :D

**Comment by ngoquang2708** [comment]
You are missing some config files on your commits. Please add it.

**Comment by koquantam** [comment]
Hmm... which one?

**Comment by ngoquang2708** [comment]
git status will show you

**Comment by koquantam** [comment]
Oh damn, it shows a bunch of conflicts

**Comment by ngoquang2708** [comment]
When using stock kernel, camera stuck at the first start, showing a black screen. But, when hit the capture button, surprise, it works! But why?????? With the kernel source that Samsung provide us, camera on stock ROM cannot work with it, does it missing somethings? Or we config it the wrong way?

**Comment by koquantam** [comment]
That's why people call Samsung is Sammy :D
Those source they provided us are outdated and not configured correctly. If you do a defconfig digging, you'll see there's a CONFIG_CAMERA_3M there, but it still doesn't work either

**Comment by ngoquang2708** [comment]
Yeah, look at the source code, seems CONFIG_CAMERA_3M does nothing.

**Comment by koquantam** [comment]
Idk what it says in stock, because stock spams logcat a lot, but in CM, camera makes services dies (phone freezes about 3s) and it's related to camera blob (camera2.scx15.so)

**Comment by ngoquang2708** [comment]
Needs some works to close this issue.

**Comment by koquantam** [comment]
There's sth interesting in kernel defconfig. I'll experiment it and reports

**Comment by koquantam** [comment]
There's CONFIG_ARCH_SCX35 in defconfig, which refers to SC8830 soc, needs to comment out it
A little off-topic: It's pretty interesting that we're in the same city and talking in English :D

**Comment by ngoquang2708** [comment]
Yeah, it is off-topic so just let it off.
Back to our issue, does comment out ```CONFIG_ARCH_SCX35``` solve it?

**Comment by koquantam** [comment]
Not tested yet. Could you try it?

**Comment by koquantam** [comment]
YESSSSSSS
CAMERA IS WORKING NOW!!!!!!!!!!!!!
Let's close this issue

**Comment by ngoquang2708** [comment]
Can you try to play the video recorded by the camera.

**Comment by koquantam** [comment]
Damn :D
It's partially works. If you tick capture, the phone freezes and shows blue color around the whole screen
But fixed partially anyway

**Comment by koquantam** [comment]
Even 3rd-party apps

**Comment by ngoquang2708** [comment]
At least it works without stock thingy.

**Comment by koquantam** [comment]
Yeah :D
We almost getting stable build now, except that damn RIL

**Comment by ngoquang2708** [comment]
Please reopen this.

**Comment by ngoquang2708** [comment]
I merged your changes but camera still not work.

**Comment by ngoquang2708** [comment]
And flashlight is not work either. I work before.

**Comment by koquantam** [comment]
Hmm... it only shows screen, but can't capture, as the phone freezes
And i thought Torch is fixed

**Comment by ngoquang2708** [comment]
I forked Torch pkg and fixed it flash dev path. Now it failed. Fork mine if
you interest.

**Comment by koquantam** [comment]
Only one small part to fix then there's no need to fork the whole tree (typo or sth)
With me Torch is still working

**Comment by koquantam** [comment]
Use git status to check it

**Comment by ngoquang2708** [comment]
I just used git to track and save my changes.

**Comment by ngoquang2708** [comment]
We should switch back to cyanogenmod defconfig, It have CONFIG_FRONT_CAMERA_SUPPORTED def, we don't.

**Comment by koquantam** [comment]
Hmm... it's defined in dcam kconfig
Just add it

**Comment by ngoquang2708** [comment]
This issue is fixed, finally. Maybe we use the wrong defconfig at the first start, we use vivalto3g-native_hw04_defconfig instead of this vivalto3g[ss]-native_hw04_defconfig <-- this have CONFIG_FRONT_CAMERA_SUPPORTED. To many defconfig files make me confuse!

**Comment by koquantam** [comment]
What... it did?
So how was the cam now?

**Comment by ngoquang2708** [comment]
It is working, but not stable, can recording video, but the the result have wrong color. I dont know that is because of camera or the video decoding part. And vlc now can use hwdecoding too, while Gallery is not.

**Comment by koquantam** [comment]
Worth :D
But youtube still dead

**Comment by ngoquang2708** [comment]
yeah, sure.

**Comment by koquantam** [comment]
It's because of video decoding part

**Comment by koquantam** [comment]
So now we have camera fixed, finally

**Comment by ngoquang2708** [comment]
When changing encoding codec to mpeg4 when recoding, it produces the correct result.

**Comment by koquantam** [comment]
Hmm... CONFIG_FRONT_CAMERA_SUPPORTED doesn't exist in my vivalto3gss-native_hw04_defconfig

**Comment by ngoquang2708** [comment]
Viewing those video on PC give I the same result as VLC on the phone, so may be the cause is encoding part, not camera part, not decoding part.

**Comment by koquantam** [comment]
Can you take pics?

**Comment by ngoquang2708** [comment]
First try, it crashes camera app. Second try, it works!e

**Comment by koquantam** [comment]
But which ss defconfig you use? I don't have CONFIG_FRONT_CAMERA_SUPPORTED

**Comment by ngoquang2708** [comment]
I switch to cyanogen defconfig and enable that def, commit now.

**Comment by ngoquang2708** [comment]
Those def files come from the zip file downloaded from Samsung open source release site.

**Comment by koquantam** [comment]
LOL, i asked you which defconfig, because there're tons of defconfig there

**Comment by ngoquang2708** [comment]
Maybe this vivaltoss3g-native_hw04_defconfig

What the hell those ss ss and sss thingy means?

**Comment by koquantam** [comment]
It means Sammy dude

**Comment by koquantam** [comment]
Have you edited sth on it?

**Comment by koquantam** [comment]
I just wondering, mint is 2mp but @corphish choose it as 3mp but still works LOL
Maybe let's testing with 5mp for us :D

**Comment by ngoquang2708** [comment]
Those setting does nothing, I guess.

**Comment by ngoquang2708** [comment]
I don't edit it or use it, just switch back to cyanogen defconfig

**Comment by koquantam** [comment]
LOL, maybe, because for now there's no such SPRD device that has 8mp cam
Really? I'm gotta test it

**Comment by koquantam** [comment]
Hah, found this:
D/SprdCameraParameters(  127): set ZSL support false

**Comment by ngoquang2708** [comment]
What was that?

**Comment by koquantam** [comment]
Zero Shutter Lag, it capture the pics directly w/o acting dumb (laggy)
Because we don't have auto-focus then this might be enabled in stock

**Comment by koquantam** [comment]
Can you test it with stock ROM, because i can't boot both stock and CM

**Comment by ngoquang2708** [comment]
OK

**Comment by ngoquang2708** [comment]
Tested, stock have it too

**Comment by koquantam** [comment]
That log?
Damn.... How it freezes the phone?

**Comment by ngoquang2708** [comment]
Waiting for audio source :D

**Comment by koquantam** [comment]
@corphish says our camera needs libbinder patch to get it working

**Comment by ngoquang2708** [comment]
We patched it using his patches.

**Comment by ngoquang2708** [comment]
Camera is now working fine with just a little unstable.

**Comment by koquantam** [comment]
Which one? I don't see it

**Comment by ngoquang2708** [comment]
https://github.com/koquantam/android_frameworks_native/commits/cm-11.0

**Comment by koquantam** [comment]
It's fixed, finally

**Comment by ngoquang2708** [comment]
Good. Just some minor issues left.
