### ISSUE TITLE
phoneserver failed to set ril.sim2.present prop

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#83]
I patched system/core/init/property_service.c for it to print pid of a process. Line ```442```:

```
                ERROR("sys_prop: permission denied pid:%d uid:%d name:%s\n",
                      cr.pid, cr.uid, msg.name);
```
Got this
```
quang@ubuntu:~$ adb shell dmesg | grep ril.sim2.present
<11>[    6.518732] C0 [           init, 1] init: sys_prop: permission denied pid:164 uid:1000 name:ril.sim2.present
quang@ubuntu:~$ adb shell ps -p 164
USER     PID   PPID  VSIZE  RSS   PRIO  NICE  RTPRI SCHED   WCHAN    PC         NAME
system    164   155   29868  540   20    0     0     0     ffffffff b6f3fea8 S /system/bin/phoneserver
```

**Comment by ngoquang2708** [comment]
Why phoneserver have uid of 1000 (system) while in init.scx15.rc:
```
service phoneserver_w /system/bin/phoneserver -m w
    class core
    user root
    group radio system shell
    disabled
    oneshot
```
@koquantam @Y300-0100

**Comment by Y300-0100** [comment]
user root
           0
group radio system shell
            1001   1000    2000

it look correct???
what give you the problem?

**Comment by ngoquang2708** [comment]
```ps``` shows that ```phoneserver``` is running as ```system```, not ```root``` as in ```init.scx15.rc```

**Comment by ngoquang2708** [comment]
And because of being run as ```system``` user, ```phoneserver``` cannot set ```ril.sim2.present``` prop. And we have to hack by manually set it in ```system.prop``` file, that is not so good.

**Comment by ngoquang2708** [comment]
mint's dev faced this problem too.
One thing to point out that, int ```system/core/init/property_setvice.c```, line ```74``` ```    { "ril.",             AID_RADIO,    0 },```.

**Comment by ngoquang2708** [comment]
@corphish

**Comment by Y300-0100** [comment]
As I can remember some Chinese dev named hacker something dsd had to be set in build prop even for cm 10

**Comment by Y300-0100** [comment]
https://github.com/HackerOO7
it took me a while.

**Comment by Y300-0100** [comment]
did u tried this
persist.multisim.config=dsds
persist.radio.multisim.config=dsds
ro.multi.rild=true

**Comment by ngoquang2708** [comment]
What do these prop do?

**Comment by koquantam** [comment]
LOL, that's for dual-SIM support only. Our RIL is different, not getting it work easily with normal scripts. Needs to hack the init as @ngoquang2708  said

**Comment by ngoquang2708** [comment]
@koquantam I don't know what you mean. Didn't we do support for Dual-SIM?

**Comment by koquantam** [comment]
Sorry, I'm answering @Y300-0100's question :/
Btw, @corphish has successfully ported separate ION driver for SPRD phones, at least with mint. It works with CM11 unpatched binder. Hope it works with CM12.1

**Comment by Y300-0100** [comment]
I don't know does this will help:

https://github.com/sprd-dev/device_sprd/blob/sprdroid4.4/scx15/init.scx15.rc

**Comment by ngoquang2708** [comment]
@koquantam our camera blobs relies on ```libbinder``` for ```MemoryHeapIon``` functions, I do not think what we could make ```MemoryHeapIon``` as a serparate library.

**Comment by ngoquang2708** [comment]
@Y300-0100 thanks for pointing it out, our board has ```init.scx15.rc```.

**Comment by ngoquang2708** [comment]
What kill me right now is why ```phoneserver``` is declared to run as ```root``` user, but actually running as ```system``` user :(

**Comment by koquantam** [comment]
LD_PRELOAD does that
Could you try removing system group from phoneserver?

**Comment by ngoquang2708** [comment]
@koquantam I will give it a try.
@Y300-0100 Did you build this ROM successfully? Any errors?

**Comment by Y300-0100** [comment]
syncing sources. 50%

**Comment by ngoquang2708** [comment]
@Y300-0100 A tips for you, build the kernel first, because some of our HAL modules relies on kernel header to be able to build.

**Comment by Y300-0100** [comment]
I noticed that. missing <include/...>

**Comment by Y300-0100** [comment]
include/linux etc

**Comment by ngoquang2708** [comment]
Yes, build the kernel first and android build system will prepare those headers for us.

**Comment by koquantam** [comment]
libmemoryheapion patch:
https://github.com/TeamButter/android_device_samsung_sprd-common/commit/873f22752ce548ae9f7ac615dc62bf92ef3bff3d

**Comment by koquantam** [comment]
Sorry for off-topic

**Comment by Y300-0100** [comment]
I was managed to build one previously but com.android.phone has stopped was killing me. any ideas on that?

**Comment by ngoquang2708** [comment]
May be you did not remove default ```ril-daemon``` service in ```init.rc```, it conflicts with ```ril-daemon``` services in ```init.vivalto3gvn_base.rc```.

**Comment by koquantam** [comment]
Don't just rm -rf'ing the system folder. You have to fully install the ROM. Stock blobs sometimes give us headache

**Comment by Y300-0100** [comment]
I did full wipe but didn't remove default ril-daemon

**Comment by koquantam** [comment]
Default RIL-daemon just gives you no signals, else no errors.

**Comment by Y300-0100** [comment]
U mean this:
#service ril-daemon /system/bin/rild
#    class main
#    socket rild stream 660 root radio
#    socket rild-debug stream 660 radio system
#    user root
#    group radio cache inet misc audio log

**Comment by ngoquang2708** [comment]
Yes, I commented it out, so no conflicts.

**Comment by ngoquang2708** [comment]
OK, some news, I patches ```init```'s ```property_service.c``` to add permission for ```system``` user to be able to set ```ril.``` prop, then I remove ```ril.sim2.present``` in ```build.prop``` and sim2 still work, no deny from dmesg.

**Comment by Y300-0100** [comment]
I don't have
 #wcdma rild service
 service ril-daemon /system/bin/rild -l /system/lib/libreference-ril_sp.so -m w -n 0

in my init.kanas3gnfc_base.rc

**Comment by ngoquang2708** [comment]
May be they are in init.scx15.rc

**Comment by ngoquang2708** [comment]
I have taken a look, it is here ```init.sc8830.rc```

**Comment by Y300-0100** [comment]
yes but it's
 service tril-daemon
[init.sc8830.rc.txt](https://github.com/koquantam/android_device_samsung_vivalto3gvn/files/149453/init.sc8830.rc.txt)

**Comment by ngoquang2708** [comment]
Of course, they are different board!

**Comment by koquantam** [comment]
@Y300-0100
tril-daemon is for TD-SCDMA phones, that only supports 2G mobile data. You can remove it

**Comment by Y300-0100** [comment]
@koquantam 
Thanks
I just compare ih24n69 root files. They are same as mine so it must be something else..

**Comment by ngoquang2708** [comment]
Using ```meld```?

**Comment by Y300-0100** [comment]
@ngoquang2708
Using meld?
Don't know what you mean?

**Comment by ngoquang2708** [comment]
```meld``` is tool to compare, merge,... It is worth trying it.

**Comment by Y300-0100** [comment]
device/samsung/kanas3gnfcxx/libs/libatchannel/AtChannel.cpp:188:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
device/samsung/kanas3gnfcxx/libs/libatchannel/AtChannel.cpp:189:68: error: 'Connect_RILD_Second' was not declared in this scope
make: *** [/home/darkside/android/out/target/product/kanas3gnfcxx/obj/SHARED_LIBRARIES/libatchannel_intermediates/AtChannel.o] Error 1
make: *** Waiting for unfinished jobs....
device/samsung/kanas3gnfcxx/libs/audio/audio_hw.c: In function 'out_write':
device/samsung/kanas3gnfcxx/libs/audio/audio_hw.c:2283:8: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]

**Comment by ngoquang2708** [comment]
@Y300-0100 You need to add ```COMMON_GLOBAL_CFLAGS += -DSEC_PRODUCT_FEATURE_RIL_CALL_DUALMODE_CDMAGSM``` in your ```BoardCnnfig.mk```. Btw, I don't know if our ```libatchannel``` and ```libsecril-client``` work for you, because different ```rild``` has different method to communicate with its clients.

**Comment by Y300-0100** [comment]
@ngoquang2708 
But I'm trying :)
For now I changed this to bypass error:
`int (*connect_rild)(HRilClient client) = i == 0 ? Connect_RILD : Connect_RILD;`

**Comment by ngoquang2708** [comment]
Do not do that, add ```COMMON_GLOBAL_CFLAGS += -DSEC_PRODUCT_FEATURE_RIL_CALL_DUALMODE_CDMAGSM``` in ```BoardConfig.mk```, that ```Connect_RILD``` function is definfed in ```libsecril-client```, read it ```Android.mk``` for more details.

**Comment by Y300-0100** [comment]
Thanks.

**Comment by ngoquang2708** [comment]
Fixed as of https://github.com/ngoquang2708/android_system_core/commit/07097e72a70225e270ad6164ad7ce1aed5106276.
