### ISSUE TITLE
cm-12.1: needs a proper SELinux configuration

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#86]

**Comment by koquantam** [comment]
Well, @halfpsych said that we've to configure a lot from the kernel, by adding policies. This would give us a lot of time, and it's a PITA. Do it if you really have time

**Comment by ngoquang2708** [comment]
I do not have time, noted here in case I forgot it.

**Comment by ngoquang2708** [comment]
Do you know to to use other GCC version. For unknown reason (may be I've updated Ubuntu to 16.04), when I build cm-12.1, it use GCC 4.6.

**Comment by koquantam** [comment]
I'm using Linaro for my builds, but it causes a lot segmentation faults
Btw, if you want to use other toolchains, do
1. Go to build/core/combo/TARGET_linux-arm.mk
- Edit "TARGET_GCC_VERSION" , "TARGET_TOOLCHAIN_ROOT" , "TARGET_TOOLS_PREFIX" to match your toolchain
2. Go to build/envsetup.sh
- Go to line 156, edit again to match your toolchain

**Comment by ngoquang2708** [comment]
It failed me at ```HOST_*``` things. Any way, thanks.

**Comment by koquantam** [comment]
I recommend using Linaro 4.8 for CM12.1, since it optimizes a lot for our ARM instruction set.

**Comment by koquantam** [comment]
Seems CM12.1 toolchain works with CM11

**Comment by ngoquang2708** [comment]
Tried Linaro 4.7 for cm11, kernel works fine, but crashing surfaceflinger.

**Comment by koquantam** [comment]
Set SELinux to Permissive
That work for me. IDK why it affects, it just a kernel implementation

**Comment by ngoquang2708** [comment]
Didn't SELinux is already permissive?

**Comment by koquantam** [comment]
I thought you changed it to Enforcing
There's a weird thing here: You will see the benchmark result decreases a lot from original GCC toolchain, but performance increase a lot. Very weird here

**Comment by ngoquang2708** [comment]
Currently, trying to clean ```ccache``` and doing anything again :(

**Comment by koquantam** [comment]
ccache -C will do that

**Comment by ngoquang2708** [comment]
Yes, waiting for it to complete, lazy of reconfig it.

**Comment by ngoquang2708** [comment]
Move to https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/issues/28.
