### ISSUE TITLE
Audio recording not work.

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#9]
May be this issue related to phone call not work.

**Comment by ngoquang2708** [comment]
I think this issue relates to permissions. Because we can receive incoming call, that mean that the audio recording is working.

**Comment by ngoquang2708** [comment]
I will try to look into stock init.rc to find out what permissions is difference from CM one.

**Comment by koquantam** [comment]
Of course, it's answerable

**Comment by ngoquang2708** [comment]
Int stock init.rc, mediaserver service have system group, in CM, it does not. When add system group to mediaserver in CM init.rc, mediaserver failed to detected the sound card! It is supported to not going that way, because it has more privilege than before. So why adding system group make it fail?

**Comment by koquantam** [comment]
Our stock is completely broken. It just does what it wants, like RIL. Our sound works perfectly so i think there's no need to set mediaserver at system group.

**Comment by ngoquang2708** [comment]
But when recording audio, logcat split out this thing:

I/MediaFocusControl(  512):  AudioFocus  requestAudioFocus() from android.media.AudioManager@425f2990com.android.soundrecorder.SoundRecorder$4@425e12c8
E/Recorder( 2141): audiosourcetype 1
D/AudioPolicyManagerBase( 1791): getInput() inputSource 1, samplingRate 8000, format 1, channelMask 10, acoustics 0
E/AudioRecord( 1791): Could not get audio input for record source 1
D/AudioSource( 1791): Start autoramp from 500000
E/StagefrightRecorder( 1791): audio source is not initialized
E/MediaRecorder( 2141): start failed: -2147483648

**Comment by ngoquang2708** [comment]
When change CM init.rc to stock init.rc, sound work! (and mediaserver has system group, of couse)

**Comment by koquantam** [comment]
Problem with the libstagefright:
E/StagefrightRecorder( 1791): audio source is not initialized

**Comment by ngoquang2708** [comment]
I have just found a way to make audio rec to work. I will do some check to ensure that it works in our current code base.

**Comment by koquantam** [comment]
OK

**Comment by ngoquang2708** [comment]
What the f*ck is this
```
I/AudioPolicyService(  131): Loaded audio policy from Samsung hawaii audio policy HAL (audio_policy)
```

**Comment by koquantam** [comment]
Hmm... it seems that comes from the property from build.prop
It uses hawaii's policy (hawaii is G313HN/HU board)

**Comment by ngoquang2708** [comment]
This issue is now resolved by PR #26

**Comment by ngoquang2708** [comment]
After make this to work, I confirm that this issue is not relate to phone call not working issue. Sorry for making many assumtions before.

**Comment by koquantam** [comment]
Everybody got their false,man
Dat phone calls refers to RIL, which requires many things to work

**Comment by ngoquang2708** [comment]
It seems mint's guys encountered this RIL problem too. I see they are working hard on it.

**Comment by koquantam** [comment]
Yeah, mint is a Spreadtrum phone too
He said RIL is working on hardware level (IMEI,signals,etc), but needs to be configured in Sammy/SPRD's way to get it fully working

**Comment by ngoquang2708** [comment]
Waiting for his works :D

**Comment by koquantam** [comment]
Hmm... i got bootloop when commit this change

**Comment by ngoquang2708** [comment]
What change?

**Comment by koquantam** [comment]
Audio policy

**Comment by ngoquang2708** [comment]
Try a clean build. I encountered it too, but it works after a clean build.

**Comment by ngoquang2708** [comment]
May be something doesn't recompile with new config.

**Comment by koquantam** [comment]
Damn, 2hrs more :(
Anyway, i've not tested yet because of bootloop, but try disabling CONFIG_SENSOR_OUTPUT_YUV to see if camera works

**Comment by ngoquang2708** [comment]
Don't forget to regenerate vendor folder

**Comment by koquantam** [comment]
Yes, already

**Comment by ngoquang2708** [comment]
I will try it when I have feet time :D

**Comment by koquantam** [comment]
It's kernel defconfig, so it's pretty fast to compile

**Comment by ngoquang2708** [comment]
Okay

**Comment by koquantam** [comment]
Gotta get some sleeps :D

**Comment by ngoquang2708** [comment]
It doesn't work.

**Comment by koquantam** [comment]
Confirmed

**Comment by ngoquang2708** [comment]
Sprd_dcam have less source code than mint kernel one

**Comment by koquantam** [comment]
IDK, just digging it :D
But mint is 2mp and ours is 3mp

**Comment by koquantam** [comment]
Damn, it crashes mediaserver with stock blob
How did you get it works?

**Comment by ngoquang2708** [comment]
I committed all my works, try compare all my repo with yours.

**Comment by koquantam** [comment]
Nothing conflicts, but why it still crash?

**Comment by ngoquang2708** [comment]
I have no idea

**Comment by ngoquang2708** [comment]
Logcat would help.

**Comment by koquantam** [comment]
Well, accidentally deleted logfile
But i remember it gives me a lot of backtraces, included audio_policy.scx15.so

**Comment by ngoquang2708** [comment]
Very easily to regenerate it.

**Comment by koquantam** [comment]
OK, log here: https://pastee.org/z95r8

**Comment by ngoquang2708** [comment]
I have no idea. It looks like mine before.

**Comment by ngoquang2708** [comment]
I make a clean build, and audio recoding is still working, why don't yours?

**Comment by koquantam** [comment]
Idk, typo or sth make it derp?

**Comment by ngoquang2708** [comment]
Does it working now?

**Comment by koquantam** [comment]
Still dead

**Comment by koquantam** [comment]
Sound is dead again

**Comment by ngoquang2708** [comment]
Now try remove audio_policy.scx15.so to see what happen.

**Comment by koquantam** [comment]
I already tried, missing -DMR0_AUDIO_BLOB in BoardConfig.mk makes audio dead
Just wondering why stock blob works with you, not me

**Comment by ngoquang2708** [comment]
I think removing MR0_AUDIO_BLOB make audio recording work with default audio_policy.

**Comment by koquantam** [comment]
Then i reports it doesn't work :D
Even @corphish encounters it

**Comment by ngoquang2708** [comment]
It is weird!

**Comment by ngoquang2708** [comment]
I have some ideas. Report later.

**Comment by ngoquang2708** [comment]
There is some SPRD_HARDWARE that I set in system/include/system/audio.h but I cannot send PR to you. See my android_system_core  commits.

**Comment by koquantam** [comment]
Lol

**Comment by ngoquang2708** [comment]
Great news, audio recording dead again, doing clean build :D

**Comment by ngoquang2708** [comment]
This time maybe build faster because I am a noob using ```make bacon``` instead of ```make -j4 bacon``` to use all CPU cores.

**Comment by ngoquang2708** [comment]
And one plus point, I use pre-built ```webviewchromium``` now. Check my repo for cherry-pick.

**Comment by koquantam** [comment]
Well, don't use make
If you make userdebug build, better use "brunch vivalto3gvn" ( it means lunch cm_vivalto3gvn-userdebug && mka bacon(similar to make but use SCHED_BATCH to ultilitizes CPU cores to make sure it's building at maximum performance))

**Comment by ngoquang2708** [comment]
Use ```make``` because of ```eng``` build :D. Now use ```make -j4``` for four cores.

**Comment by ngoquang2708** [comment]
Can I use ```mka``` for eng after ```lunch```? ```SCHED_BATCH``` attracts I.

**Comment by ngoquang2708** [comment]
Found this
```
envsetup.sh:- mkap:     Builds the module(s) using mka and pushes them to the device.
```
No more copying!

**Comment by koquantam** [comment]
Yes

**Comment by ngoquang2708** [comment]
Never found this without your hints, thanks.

**Comment by ngoquang2708** [comment]
Try this  [libaudioflinger.so.zip](https://github.com/koquantam/android_device_samsung_vivalto3gvn/files/117513/libaudioflinger.so.zip)

**Comment by koquantam** [comment]
What does it do?

**Comment by ngoquang2708** [comment]
It solves my audio recording issue.

**Comment by ngoquang2708** [comment]
OK, I will do more tests.

**Comment by koquantam** [comment]
It's the same as my lib, but how there's sth that works with you, not mine and opposite? It's supposed to works with both LOL

**Comment by ngoquang2708** [comment]
Please close this if it works now.

**Comment by koquantam** [comment]
OK, i'll check it
Compiling CM12.1 now :D

**Comment by ngoquang2708** [comment]
OK

**Comment by koquantam** [comment]
Confirmed

**Comment by koquantam** [comment]
Dude, remove that stock APM blob. Without it, audio and recording still works.

**Comment by koquantam** [comment]
We have audio_policy.default carry that, so it's OK

**Comment by ngoquang2708** [comment]
I don't like stock audio blobs, It gives me headaches. I still keep it because it makes speaker works in call. But as you asked. I will remove it.
